/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DocumentShortDto } from '../../models/document-short-dto';

export interface GetEmployeeDocuments$Params {

/**
 * ID de l'employé
 */
  employeeId: number;
}

export function getEmployeeDocuments(http: HttpClient, rootUrl: string, params: GetEmployeeDocuments$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<DocumentShortDto>>> {
  const rb = new RequestBuilder(rootUrl, getEmployeeDocuments.PATH, 'get');
  if (params) {
    rb.path('employeeId', params.employeeId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<DocumentShortDto>>;
    })
  );
}

getEmployeeDocuments.PATH = '/documents/employees/{employeeId}';
