/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface GetEmployeeDocumentContent$Params {

/**
 * ID de l'employé
 */
  employeeId: number;

/**
 * ID du document
 */
  documentId: number;
}

export function getEmployeeDocumentContent(http: HttpClient, rootUrl: string, params: GetEmployeeDocumentContent$Params, context?: HttpContext): Observable<StrictHttpResponse<Blob>> {
  const rb = new RequestBuilder(rootUrl, getEmployeeDocumentContent.PATH, 'get');
  if (params) {
    rb.path('employeeId', params.employeeId, {});
    rb.path('documentId', params.documentId, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Blob>;
    })
  );
}

getEmployeeDocumentContent.PATH = '/documents/employees/{employeeId}/{documentId}/content';
