/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DocumentShortDto } from '../../models/document-short-dto';

export interface GetDocumentsByType$Params {

/**
 * Type de document
 */
  type: 'CV' | 'IDENTITY' | 'DIPLOMA' | 'CONTRACT' | 'PAYSLIP' | 'CERTIFICATE' | 'ADMINISTRATIVE' | 'OTHER';
}

export function getDocumentsByType(http: HttpClient, rootUrl: string, params: GetDocumentsByType$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<DocumentShortDto>>> {
  const rb = new RequestBuilder(rootUrl, getDocumentsByType.PATH, 'get');
  if (params) {
    rb.path('type', params.type, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<DocumentShortDto>>;
    })
  );
}

getDocumentsByType.PATH = '/documents/types/{type}';
