/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DocumentDto } from '../../models/document-dto';

export interface UploadContractDocument$Params {
  contractId: number;
  type: 'CV' | 'IDENTITY' | 'DIPLOMA' | 'CONTRACT' | 'PAYSLIP' | 'CERTIFICATE' | 'ADMINISTRATIVE' | 'OTHER';
  name?: string;
  body?: {
    file: Blob;
  } | FormData;
}

export function uploadContractDocument(http: HttpClient, rootUrl: string, params: UploadContractDocument$Params, context?: HttpContext): Observable<StrictHttpResponse<DocumentDto>> {
  const rb = new RequestBuilder(rootUrl, uploadContractDocument.PATH, 'post');
  if (params) {
    rb.path('contractId', params.contractId, {});
    rb.query('type', params.type, {});
    if (params.name) {
      rb.query('name', params.name, {});
    }

    const formData = new FormData();

    if (params.body instanceof FormData) {
      return http.post<DocumentDto>(
        `${rootUrl}${uploadContractDocument.PATH.replace('{contractId}', params.contractId.toString())}`,
        params.body,
        {
          params: {
            type: params.type,
            ...(params.name ? { name: params.name } : {})
          },
          observe: 'response',
          responseType: 'json',
          context
        }
      ).pipe(
        filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
        map((r: HttpResponse<any>) => r as StrictHttpResponse<DocumentDto>)
      );
    } else if (params.body && 'file' in params.body) {
      formData.append('file', params.body.file);

      return http.post<DocumentDto>(
        `${rootUrl}${uploadContractDocument.PATH.replace('{contractId}', params.contractId.toString())}`,
        formData,
        {
          params: {
            type: params.type,
            ...(params.name ? { name: params.name } : {})
          },
          observe: 'response',
          responseType: 'json',
          context
        }
      ).pipe(
        filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
        map((r: HttpResponse<any>) => r as StrictHttpResponse<DocumentDto>)
      );
    }
  }

  // Fallback to original implementation
  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DocumentDto>;
    })
  );
}

uploadContractDocument.PATH = '/documents/contracts/{contractId}';
