/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DocumentDto } from '../../models/document-dto';

export interface UploadContractDocument$Params {

/**
 * ID du contrat
 */
  contractId: number;

/**
 * Type de document
 */
  type: 'CV' | 'IDENTITY' | 'DIPLOMA' | 'CONTRACT' | 'PAYSLIP' | 'CERTIFICATE' | 'ADMINISTRATIVE' | 'OTHER';

/**
 * Nom du document (optionnel)
 */
  name?: string;
      body?: {

/**
 * Fichier à uploader
 */
'file': Blob;
}
}

export function uploadContractDocument(http: HttpClient, rootUrl: string, params: UploadContractDocument$Params, context?: HttpContext): Observable<StrictHttpResponse<DocumentDto>> {
  const rb = new RequestBuilder(rootUrl, uploadContractDocument.PATH, 'post');
  if (params) {
    rb.path('contractId', params.contractId, {});
    rb.query('type', params.type, {});
    rb.query('name', params.name, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DocumentDto>;
    })
  );
}

uploadContractDocument.PATH = '/documents/contracts/{contractId}';
