/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DepartmentAbsenteeismDto } from '../models/department-absenteeism-dto';
import { LeaveTypeAbsenteeismDto } from '../models/leave-type-absenteeism-dto';
import { MonthlyAbsenteeismDto } from '../models/monthly-absenteeism-dto';
export interface AbsenteeismReportDto {
  absenteeismRate?: number;
  departmentAbsenteeism?: Array<DepartmentAbsenteeismDto>;
  leaveTypeAbsenteeism?: Array<LeaveTypeAbsenteeismDto>;
  monthlyAbsenteeism?: Array<MonthlyAbsenteeismDto>;
  totalAbsenceDays?: number;
  totalEmployees?: number;
  totalWorkingDays?: number;
  year?: number;
}
