/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AgeDistributionDto {
  age25to34Count?: number;
  age35to44Count?: number;
  age45to54Count?: number;
  age55plusCount?: number;
  averageAge?: number;
  averageAgeByDepartment?: {
[key: string]: number;
};
  under25Count?: number;
}
