/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Requête d'authentification
 */
export interface AuthenticationRequest {
  email: string;
  password: string;
}
