/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ContractUpdateDto {
  endDate?: string;
  salary?: number;
  startDate?: string;
  type?: 'CDI' | 'CDD' | 'STAGE' | 'INTERIM' | 'FREELANCE' | 'APPRENTICESHIP' | 'PART_TIME';
  workHoursPerWeek?: number;
}
