/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DepartementCreateDto {
  active?: boolean;
  code?: string;
  description?: string;
  managerId?: number;
  name?: string;
  parentDepartementId?: number;
}
