/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DepartmentAbsenteeismDto {
  absenceDays?: number;
  absenteeismRate?: number;
  departmentId?: number;
  departmentName?: string;
  totalEmployees?: number;
}
