/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DepartmentSalaryCostDto {
  averageSalary?: number;
  departmentId?: number;
  departmentName?: string;
  employeeCount?: number;
  percentageOfTotal?: number;
  totalCost?: number;
}
