/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DepartmentEmployeeStatsDto {
  activeEmployees?: number;
  departmentCode?: string;
  departmentId?: number;
  departmentName?: string;
  inactiveEmployees?: number;
  onLeaveEmployees?: number;
  totalEmployees?: number;
}
