/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DepartmentTurnoverDto {
  departmentId?: number;
  departmentName?: string;
  departures?: number;
  endEmployeeCount?: number;
  newHires?: number;
  startEmployeeCount?: number;
  turnoverRate?: number;
}
