/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EmployeeShortDto } from '../models/employee-short-dto';
export interface DepartementTreeDto {
  active?: boolean;
  code?: string;
  id?: number;
  manager?: EmployeeShortDto;
  name?: string;
}
