/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DocumentUpdateDto {
  name?: string;
  type?: 'CV' | 'IDENTITY' | 'DIPLOMA' | 'CONTRACT' | 'PAYSLIP' | 'CERTIFICATE' | 'ADMINISTRATIVE' | 'OTHER';
}
