/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DocumentShortDto {
  id?: number;
  name?: string;
  type?: 'CV' | 'IDENTITY' | 'DIPLOMA' | 'CONTRACT' | 'PAYSLIP' | 'CERTIFICATE' | 'ADMINISTRATIVE' | 'OTHER';
  uploadDate?: string;
}
