/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface EmployeeCreateDto {
  address?: string;
  bankAccountInfo?: string;
  birthDate?: string;
  city?: string;
  departementId?: number;
  emergencyContactName?: string;
  emergencyContactPhone?: string;
  firstName?: string;
  gender?: 'MALE' | 'FEMALE';
  hireDate?: string;
  lastName?: string;
  managerId?: number;
  phone?: string;
  positionId?: number;
  socialSecurityNumber?: string;
  status?: 'ACTIVE' | 'INACTIVE' | 'ON_LEAVE' | 'TERMINATED';
}
