/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface EmployeeUpdateDto {
  address?: string;
  bankAccountInfo?: string;
  birthDate?: string;
  city?: string;
  departementId?: number;
  emergencyContactName?: string;
  emergencyContactPhone?: string;
  firstName?: string;
  gender?: 'MALE' | 'FEMALE';
  lastName?: string;
  managerId?: number;
  phone?: string;
  positionId?: number;
  socialSecurityNumber?: string;
}
