/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AgeDistributionDto } from '../models/age-distribution-dto';
import { GenderDistributionDto } from '../models/gender-distribution-dto';
import { SeniorityDistributionDto } from '../models/seniority-distribution-dto';
export interface EmployeeDistributionReportDto {
  ageDistribution?: AgeDistributionDto;
  contractTypeDistribution?: {
[key: string]: number;
};
  departmentDistribution?: {
[key: string]: number;
};
  genderDistribution?: GenderDistributionDto;
  positionDistribution?: {
[key: string]: number;
};
  seniorityDistribution?: SeniorityDistributionDto;
  statusDistribution?: {
[key: string]: number;
};
  totalEmployees?: number;
}
