/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface GenderDistributionDto {
  byDepartment?: {
[key: string]: GenderDistributionDto;
};
  byPosition?: {
[key: string]: GenderDistributionDto;
};
  femaleCount?: number;
  femalePercentage?: number;
  maleCount?: number;
  malePercentage?: number;
}
