/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface LeavePolicyDto {
  carryForwardAllowed?: boolean;
  defaultDays?: number;
  description?: string;
  id?: number;
  isPaid?: boolean;
  leaveType?: 'ANNUAL_LEAVE' | 'SICK_LEAVE' | 'MATERNITY_LEAVE' | 'PATERNITY_LEAVE' | 'UNPAID_LEAVE' | 'BEREAVEMENT_LEAVE' | 'MARRIAGE_LEAVE' | 'TRAINING_LEAVE' | 'SABBATICAL_LEAVE' | 'OTHER';
  maxCarryForwardDays?: number;
  maxConsecutiveDays?: number;
  minRequestNoticeDays?: number;
  requiresApproval?: boolean;
  requiresDocumentation?: boolean;
  year?: number;
}
