/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EmployeeShortDto } from '../models/employee-short-dto';
import { LeaveDto } from '../models/leave-dto';
export interface LeaveEmployeeSummaryDto {
  annualLeaveBalance?: number;
  employee?: EmployeeShortDto;
  pendingLeaves?: number;
  sickLeaveBalance?: number;
  totalLeavesThisYear?: number;
  upcomingLeaves?: Array<LeaveDto>;
}
