/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MonthlyTurnoverDto {
  departures?: number;
  month?: number;
  monthName?: string;
  newHires?: number;
  turnoverRate?: number;
  year?: number;
}
