/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MonthlySalaryCostDto {
  averageSalary?: number;
  employeeCount?: number;
  month?: number;
  monthName?: string;
  totalCost?: number;
  year?: number;
}
