/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MonthlyAbsenteeismDto {
  absenceDays?: number;
  absenteeismRate?: number;
  month?: number;
  monthName?: string;
  totalEmployees?: number;
  workingDays?: number;
  year?: number;
}
