/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Détails de la position à créer
 */
export interface PositionCreateDto {
  active?: boolean;
  departmentId?: number;
  description?: string;
  grade: string;
  maxSalary: number;
  minSalary: number;
  requirements?: string;
  responsibilities?: string;
  title: string;
}
