/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Détails mis à jour de la position
 */
export interface PositionUpdateDto {
  active?: boolean;
  departmentId?: number;
  description?: string;
  grade?: string;
  maxSalary?: number;
  minSalary?: number;
  requirements?: string;
  responsibilities?: string;
  title?: string;
}
