/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DepartmentSalaryCostDto } from '../models/department-salary-cost-dto';
import { MonthlySalaryCostDto } from '../models/monthly-salary-cost-dto';
export interface SalaryCostReportDto {
  averageSalary?: number;
  costByContractType?: {
[key: string]: number;
};
  departmentCosts?: Array<DepartmentSalaryCostDto>;
  maxSalary?: number;
  medianSalary?: number;
  minSalary?: number;
  monthlyCosts?: Array<MonthlySalaryCostDto>;
  totalSalaryCost?: number;
  year?: number;
}
