/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SeniorityDistributionDto {
  averageSeniority?: number;
  averageSeniorityByDepartment?: {
[key: string]: number;
};
  fiveToTenYearsCount?: number;
  lessThan1YearCount?: number;
  moreThanTenYearsCount?: number;
  oneToThreeYearsCount?: number;
  threeToFiveYearsCount?: number;
}
