/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserDto {
  accountLocked?: boolean;
  email?: string;
  enabled?: boolean;
  fullName?: string;
  id?: number;
  lastLogin?: string;
  roles?: Array<string>;
  username?: string;
}
