/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DepartementTreeDto } from '../../models/departement-tree-dto';

export interface GetOrganizationChart$Params {
}

export function getOrganizationChart(http: HttpClient, rootUrl: string, params?: GetOrganizationChart$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<DepartementTreeDto>>> {
  const rb = new RequestBuilder(rootUrl, getOrganizationChart.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<DepartementTreeDto>>;
    })
  );
}

getOrganizationChart.PATH = '/organizations/chart';
