/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ContractDto } from '../../models/contract-dto';

export interface GetExpiringContracts$Params {

/**
 * Nombre de jours avant expiration
 */
  arg0?: number;
}

export function getExpiringContracts(http: HttpClient, rootUrl: string, params?: GetExpiringContracts$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ContractDto>>> {
  const rb = new RequestBuilder(rootUrl, getExpiringContracts.PATH, 'get');
  if (params) {
    rb.query('arg0', params.arg0, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ContractDto>>;
    })
  );
}

getExpiringContracts.PATH = '/contracts/expiring';
