/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ContractDto } from '../../models/contract-dto';

export interface GetContractsByStatus$Params {
}

export function getContractsByStatus(http: HttpClient, rootUrl: string, params?: GetContractsByStatus$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ContractDto>>> {
  const rb = new RequestBuilder(rootUrl, getContractsByStatus.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ContractDto>>;
    })
  );
}

getContractsByStatus.PATH = '/contracts/status/{status}';
