/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ContractDto } from '../../models/contract-dto';

export interface GetContractsByType$Params {

/**
 * Type de contrat
 */
  type: 'CDI' | 'CDD' | 'STAGE' | 'INTERIM' | 'FREELANCE' | 'APPRENTICESHIP' | 'PART_TIME';
}

export function getContractsByType(http: HttpClient, rootUrl: string, params: GetContractsByType$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ContractDto>>> {
  const rb = new RequestBuilder(rootUrl, getContractsByType.PATH, 'get');
  if (params) {
    rb.path('type', params.type, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ContractDto>>;
    })
  );
}

getContractsByType.PATH = '/contracts/type/{type}';
