/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Pageable } from '../../models/pageable';
import { PageContractDto } from '../../models/page-contract-dto';

export interface SearchContracts$Params {

/**
 * Mot-clé pour la recherche dans le nom de l'employé
 */
  keyword?: string;

/**
 * Type de contrat
 */
  type?: 'CDI' | 'CDD' | 'STAGE' | 'INTERIM' | 'FREELANCE' | 'APPRENTICESHIP' | 'PART_TIME';

/**
 * Statut du contrat
 */
  status?: 'DRAFT' | 'PENDING' | 'ACTIVE' | 'EXPIRED' | 'TERMINATED' | 'RENEWED';

/**
 * Date de début minimum (format yyyy-MM-dd)
 */
  startDateMin?: string;

/**
 * Date de début maximum (format yyyy-MM-dd)
 */
  startDateMax?: string;
  pageable: Pageable;
}

export function searchContracts(http: HttpClient, rootUrl: string, params: SearchContracts$Params, context?: HttpContext): Observable<StrictHttpResponse<PageContractDto>> {
  const rb = new RequestBuilder(rootUrl, searchContracts.PATH, 'get');
  if (params) {
    rb.query('keyword', params.keyword, {});
    rb.query('type', params.type, {});
    rb.query('status', params.status, {});
    rb.query('startDateMin', params.startDateMin, {});
    rb.query('startDateMax', params.startDateMax, {});
    rb.query('pageable', params.pageable, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageContractDto>;
    })
  );
}

searchContracts.PATH = '/contracts/search';
