/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Pageable } from '../../models/pageable';
import { PageContractDto } from '../../models/page-contract-dto';

export interface SearchContracts$Params {

/**
 * Mot-clé pour la recherche dans le nom de l'employé
 */
  arg0?: string;

/**
 * Type de contrat
 */
  arg1?: 'CDI' | 'CDD' | 'STAGE' | 'INTERIM' | 'FREELANCE' | 'APPRENTICESHIP' | 'PART_TIME';

/**
 * Statut du contrat
 */
  arg2?: 'DRAFT' | 'PENDING' | 'ACTIVE' | 'EXPIRED' | 'TERMINATED' | 'RENEWED';

/**
 * Date de début minimum (format yyyy-MM-dd)
 */
  arg3?: string;

/**
 * Date de début maximum (format yyyy-MM-dd)
 */
  arg4?: string;
  arg5: Pageable;
}

export function searchContracts(http: HttpClient, rootUrl: string, params: SearchContracts$Params, context?: HttpContext): Observable<StrictHttpResponse<PageContractDto>> {
  const rb = new RequestBuilder(rootUrl, searchContracts.PATH, 'get');
  if (params) {
    rb.query('arg0', params.arg0, {});
    rb.query('arg1', params.arg1, {});
    rb.query('arg2', params.arg2, {});
    rb.query('arg3', params.arg3, {});
    rb.query('arg4', params.arg4, {});
    rb.query('arg5', params.arg5, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageContractDto>;
    })
  );
}

searchContracts.PATH = '/contracts/search';
