/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PositionCreateDto } from '../../models/position-create-dto';
import { PositionDto } from '../../models/position-dto';

export interface CreatePosition$Params {
      body: PositionCreateDto
}

export function createPosition(http: HttpClient, rootUrl: string, params: CreatePosition$Params, context?: HttpContext): Observable<StrictHttpResponse<PositionDto>> {
  const rb = new RequestBuilder(rootUrl, createPosition.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PositionDto>;
    })
  );
}

createPosition.PATH = '/api/positions';
