/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PositionDto } from '../../models/position-dto';

export interface GetPositionById$Params {

/**
 * ID de la position
 */
  id: number;
}

export function getPositionById(http: HttpClient, rootUrl: string, params: GetPositionById$Params, context?: HttpContext): Observable<StrictHttpResponse<PositionDto>> {
  const rb = new RequestBuilder(rootUrl, getPositionById.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PositionDto>;
    })
  );
}

getPositionById.PATH = '/api/positions/{id}';
