/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface GetPositionsBySalaryRange$Params {

/**
 * Salaire minimum
 */
  minSalary: number;

/**
 * Salaire maximum
 */
  maxSalary: number;
}

export function getPositionsBySalaryRange(http: HttpClient, rootUrl: string, params: GetPositionsBySalaryRange$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
  const rb = new RequestBuilder(rootUrl, getPositionsBySalaryRange.PATH, 'get');
  if (params) {
    rb.query('minSalary', params.minSalary, {});
    rb.query('maxSalary', params.maxSalary, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<string>;
    })
  );
}

getPositionsBySalaryRange.PATH = '/api/positions/salary-range';
