/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Page } from '../../models/page';
import { Pageable } from '../../models/pageable';

export interface SearchPositions$Params {

/**
 * Mot-clé pour la recherche (titre ou description)
 */
  arg0?: string;

/**
 * Filtrer par statut actif/inactif
 */
  arg1?: boolean;

/**
 * Filtrer par département
 */
  arg2?: number;

/**
 * Paramètres de pagination
 */
  arg3: Pageable;
}

export function searchPositions(http: HttpClient, rootUrl: string, params: SearchPositions$Params, context?: HttpContext): Observable<StrictHttpResponse<Page>> {
  const rb = new RequestBuilder(rootUrl, searchPositions.PATH, 'get');
  if (params) {
    rb.query('arg0', params.arg0, {});
    rb.query('arg1', params.arg1, {});
    rb.query('arg2', params.arg2, {});
    rb.query('arg3', params.arg3, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Page>;
    })
  );
}

searchPositions.PATH = '/api/positions/search';
