/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PositionDto } from '../../models/position-dto';

export interface UpdatePositionStatus$Params {

/**
 * Nouveau statut (true = actif, false = inactif)
 */
  arg1: boolean;
}

export function updatePositionStatus(http: HttpClient, rootUrl: string, params: UpdatePositionStatus$Params, context?: HttpContext): Observable<StrictHttpResponse<PositionDto>> {
  const rb = new RequestBuilder(rootUrl, updatePositionStatus.PATH, 'patch');
  if (params) {
    rb.query('arg1', params.arg1, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PositionDto>;
    })
  );
}

updatePositionStatus.PATH = '/api/positions/{id}/status';
