/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface CheckOverlappingLeave$Params {

/**
 * ID de l'employé
 */
  employeeId: number;

/**
 * Date de début
 */
  startDate: string;

/**
 * Date de fin
 */
  endDate: string;

/**
 * ID de la demande à exclure
 */
  excludeLeaveId?: number;
}

export function checkOverlappingLeave(http: HttpClient, rootUrl: string, params: CheckOverlappingLeave$Params, context?: HttpContext): Observable<StrictHttpResponse<boolean>> {
  const rb = new RequestBuilder(rootUrl, checkOverlappingLeave.PATH, 'get');
  if (params) {
    rb.query('employeeId', params.employeeId, {});
    rb.query('startDate', params.startDate, {});
    rb.query('endDate', params.endDate, {});
    rb.query('excludeLeaveId', params.excludeLeaveId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: String((r as HttpResponse<any>).body) === 'true' }) as StrictHttpResponse<boolean>;
    })
  );
}

checkOverlappingLeave.PATH = '/leaves/overlap';
