/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { LeaveCreateDto } from '../../models/leave-create-dto';
import { LeaveDto } from '../../models/leave-dto';

export interface CreateLeave$Params {
      body: LeaveCreateDto
}

export function createLeave(http: HttpClient, rootUrl: string, params: CreateLeave$Params, context?: HttpContext): Observable<StrictHttpResponse<LeaveDto>> {
  const rb = new RequestBuilder(rootUrl, createLeave.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<LeaveDto>;
    })
  );
}

createLeave.PATH = '/leaves';
