/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { LeaveDto } from '../../models/leave-dto';

export interface GetPendingLeavesByManager$Params {

/**
 * ID du manager
 */
  managerId: number;
}

export function getPendingLeavesByManager(http: HttpClient, rootUrl: string, params: GetPendingLeavesByManager$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<LeaveDto>>> {
  const rb = new RequestBuilder(rootUrl, getPendingLeavesByManager.PATH, 'get');
  if (params) {
    rb.path('managerId', params.managerId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<LeaveDto>>;
    })
  );
}

getPendingLeavesByManager.PATH = '/leaves/pending/manager/{managerId}';
