/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { LeaveDto } from '../../models/leave-dto';

export interface GetLeaveById$Params {

/**
 * ID de la demande de congés
 */
  id: number;
}

export function getLeaveById(http: HttpClient, rootUrl: string, params: GetLeaveById$Params, context?: HttpContext): Observable<StrictHttpResponse<LeaveDto>> {
  const rb = new RequestBuilder(rootUrl, getLeaveById.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<LeaveDto>;
    })
  );
}

getLeaveById.PATH = '/leaves/{id}';
