/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Pageable } from '../../models/pageable';
import { PageLeaveDto } from '../../models/page-leave-dto';

export interface SearchLeaves$Params {

/**
 * ID de l'employé
 */
  employeeId?: number;

/**
 * Statut de la demande
 */
  status?: 'PENDING' | 'APPROVED' | 'REJECTED' | 'CANCELLED' | 'IN_PROGRESS' | 'COMPLETED';

/**
 * Type de congés
 */
  leaveType?: 'ANNUAL_LEAVE' | 'SICK_LEAVE' | 'MATERNITY_LEAVE' | 'PATERNITY_LEAVE' | 'UNPAID_LEAVE' | 'BEREAVEMENT_LEAVE' | 'MARRIAGE_LEAVE' | 'TRAINING_LEAVE' | 'SABBATICAL_LEAVE' | 'OTHER';

/**
 * Date de début minimum
 */
  startDateMin?: string;

/**
 * Date de début maximum
 */
  startDateMax?: string;

/**
 * ID de l'approbateur
 */
  approvedById?: number;
  pageable: Pageable;
}

export function searchLeaves(http: HttpClient, rootUrl: string, params: SearchLeaves$Params, context?: HttpContext): Observable<StrictHttpResponse<PageLeaveDto>> {
  const rb = new RequestBuilder(rootUrl, searchLeaves.PATH, 'get');
  if (params) {
    rb.query('employeeId', params.employeeId, {});
    rb.query('status', params.status, {});
    rb.query('leaveType', params.leaveType, {});
    rb.query('startDateMin', params.startDateMin, {});
    rb.query('startDateMax', params.startDateMax, {});
    rb.query('approvedById', params.approvedById, {});
    rb.query('pageable', params.pageable, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageLeaveDto>;
    })
  );
}

searchLeaves.PATH = '/leaves/search';
