/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { LeaveDto } from '../../models/leave-dto';
import { LeaveUpdateDto } from '../../models/leave-update-dto';

export interface UpdateLeave$Params {

/**
 * ID de la demande de congés
 */
  id: number;
      body: LeaveUpdateDto
}

export function updateLeave(http: HttpClient, rootUrl: string, params: UpdateLeave$Params, context?: HttpContext): Observable<StrictHttpResponse<LeaveDto>> {
  const rb = new RequestBuilder(rootUrl, updateLeave.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<LeaveDto>;
    })
  );
}

updateLeave.PATH = '/leaves/{id}';
