/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { LeaveBalanceAdjustmentDto } from '../../models/leave-balance-adjustment-dto';
import { LeaveBalanceDto } from '../../models/leave-balance-dto';

export interface AdjustLeaveBalance$Params {

/**
 * ID du solde de congés
 */
  id: number;
      body: LeaveBalanceAdjustmentDto
}

export function adjustLeaveBalance(http: HttpClient, rootUrl: string, params: AdjustLeaveBalance$Params, context?: HttpContext): Observable<StrictHttpResponse<LeaveBalanceDto>> {
  const rb = new RequestBuilder(rootUrl, adjustLeaveBalance.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<LeaveBalanceDto>;
    })
  );
}

adjustLeaveBalance.PATH = '/leave-balances/{id}/adjust';
