/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { LeaveBalanceDto } from '../../models/leave-balance-dto';

export interface GetEmployeeLeaveBalances$Params {

/**
 * ID de l'employé
 */
  employeeId: number;
}

export function getEmployeeLeaveBalances(http: HttpClient, rootUrl: string, params: GetEmployeeLeaveBalances$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<LeaveBalanceDto>>> {
  const rb = new RequestBuilder(rootUrl, getEmployeeLeaveBalances.PATH, 'get');
  if (params) {
    rb.path('employeeId', params.employeeId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<LeaveBalanceDto>>;
    })
  );
}

getEmployeeLeaveBalances.PATH = '/leave-balances/employee/{employeeId}';
