/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { LeaveBalanceDto } from '../../models/leave-balance-dto';

export interface GetAllLeaveBalances$Params {
}

export function getAllLeaveBalances(http: HttpClient, rootUrl: string, params?: GetAllLeaveBalances$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<LeaveBalanceDto>>> {
  const rb = new RequestBuilder(rootUrl, getAllLeaveBalances.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<LeaveBalanceDto>>;
    })
  );
}

getAllLeaveBalances.PATH = '/leave-balances';
