/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { LeaveBalanceDto } from '../../models/leave-balance-dto';

export interface GetLeaveBalanceById$Params {

/**
 * ID du solde de congés
 */
  id: number;
}

export function getLeaveBalanceById(http: HttpClient, rootUrl: string, params: GetLeaveBalanceById$Params, context?: HttpContext): Observable<StrictHttpResponse<LeaveBalanceDto>> {
  const rb = new RequestBuilder(rootUrl, getLeaveBalanceById.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<LeaveBalanceDto>;
    })
  );
}

getLeaveBalanceById.PATH = '/leave-balances/{id}';
