/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { NgModule, ModuleWithProviders, SkipSelf, Optional } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { ApiConfiguration, ApiConfigurationParams } from './api-configuration';

import { CongesService } from './services/conges.service';
import { PolitiquesDeCongesService } from './services/politiques-de-conges.service';
import { EmployeeService } from './services/employee.service';
import { DocumentManagementService } from './services/document-management.service';
import { DepartementsService } from './services/departements.service';
import { ContratsService } from './services/contrats.service';
import { PositionsService } from './services/positions.service';
import { SoldesDeCongesService } from './services/soldes-de-conges.service';
import { AuthenticationService } from './services/authentication.service';
import { RapportsService } from './services/rapports.service';
import { OrganisationService } from './services/organisation.service';

/**
 * Module that provides all services and configuration.
 */
@NgModule({
  imports: [],
  exports: [],
  declarations: [],
  providers: [
    CongesService,
    PolitiquesDeCongesService,
    EmployeeService,
    DocumentManagementService,
    DepartementsService,
    ContratsService,
    PositionsService,
    SoldesDeCongesService,
    AuthenticationService,
    RapportsService,
    OrganisationService,
    ApiConfiguration
  ],
})
export class ApiModule {
  static forRoot(params: ApiConfigurationParams): ModuleWithProviders<ApiModule> {
    return {
      ngModule: ApiModule,
      providers: [
        {
          provide: ApiConfiguration,
          useValue: params
        }
      ]
    }
  }

  constructor( 
    @Optional() @SkipSelf() parentModule: ApiModule,
    @Optional() http: HttpClient
  ) {
    if (parentModule) {
      throw new Error('ApiModule is already loaded. Import in your base AppModule only.');
    }
    if (!http) {
      throw new Error('You need to import the HttpClientModule in your AppModule! \n' +
      'See also https://github.com/angular/angular/issues/20575');
    }
  }
}
