/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { AuthenticationRequest } from './models/authentication-request';
export type { AuthenticationResponse } from './models/authentication-response';
export type { ContractCreateDto } from './models/contract-create-dto';
export type { ContractDto } from './models/contract-dto';
export type { ContractStatusUpdateDto } from './models/contract-status-update-dto';
export type { ContractUpdateDto } from './models/contract-update-dto';
export type { DepartementCreateDto } from './models/departement-create-dto';
export type { DepartementDto } from './models/departement-dto';
export type { DepartementShortDto } from './models/departement-short-dto';
export type { DepartementTreeDto } from './models/departement-tree-dto';
export type { DepartementUpdateDto } from './models/departement-update-dto';
export type { DepartmentEmployeeStatsDto } from './models/department-employee-stats-dto';
export type { DocumentDto } from './models/document-dto';
export type { DocumentShortDto } from './models/document-short-dto';
export type { DocumentUpdateDto } from './models/document-update-dto';
export type { EmployeeCreateDto } from './models/employee-create-dto';
export type { EmployeeDto } from './models/employee-dto';
export type { EmployeeShortDto } from './models/employee-short-dto';
export type { EmployeeStatusUpdateDto } from './models/employee-status-update-dto';
export type { EmployeeUpdateDto } from './models/employee-update-dto';
export type { Page } from './models/page';
export type { Pageable } from './models/pageable';
export type { PageableObject } from './models/pageable-object';
export type { PageContractDto } from './models/page-contract-dto';
export type { PageDepartementDto } from './models/page-departement-dto';
export type { PageDocumentShortDto } from './models/page-document-short-dto';
export type { PageEmployeeDto } from './models/page-employee-dto';
export type { PageEmployeeShortDto } from './models/page-employee-short-dto';
export type { PositionCreateDto } from './models/position-create-dto';
export type { PositionDto } from './models/position-dto';
export type { PositionUpdateDto } from './models/position-update-dto';
export type { SortObject } from './models/sort-object';
export type { UserDto } from './models/user-dto';
