/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { CongesService } from './services/conges.service';
export { PolitiquesDeCongesService } from './services/politiques-de-conges.service';
export { EmployeeService } from './services/employee.service';
export { DocumentManagementService } from './services/document-management.service';
export { DepartementsService } from './services/departements.service';
export { ContratsService } from './services/contrats.service';
export { PositionsService } from './services/positions.service';
export { SoldesDeCongesService } from './services/soldes-de-conges.service';
export { AuthenticationService } from './services/authentication.service';
export { RapportsService } from './services/rapports.service';
export { OrganisationService } from './services/organisation.service';
