/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { EmployeeService } from './services/employee.service';
export { DocumentManagementService } from './services/document-management.service';
export { DepartementsService } from './services/departements.service';
export { ContratsService } from './services/contrats.service';
export { PositionsService } from './services/positions.service';
export { AuthenticationService } from './services/authentication.service';
export { OrganisationService } from './services/organisation.service';
