/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface GenerateReport$Params {

/**
 * Type de rapport (turnover, absenteeism, salary, distribution)
 */
  reportType: string;

/**
 * Année pour le rapport (par défaut: année courante)
 */
  year?: number;

/**
 * Date de début pour les rapports sur une période spécifique
 */
  startDate?: string;

/**
 * Date de fin pour les rapports sur une période spécifique
 */
  endDate?: string;

/**
 * Date de référence pour les rapports à une date précise
 */
  referenceDate?: string;

/**
 * Format du rapport (PDF, EXCEL, CSV)
 */
  format?: string;
}

export function generateReport(http: HttpClient, rootUrl: string, params: GenerateReport$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
  const rb = new RequestBuilder(rootUrl, generateReport.PATH, 'get');
  if (params) {
    rb.query('reportType', params.reportType, {});
    rb.query('year', params.year, {});
    rb.query('startDate', params.startDate, {});
    rb.query('endDate', params.endDate, {});
    rb.query('referenceDate', params.referenceDate, {});
    rb.query('format', params.format, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<string>;
    })
  );
}

generateReport.PATH = '/reports/generate';
