/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { EmployeeDistributionReportDto } from '../../models/employee-distribution-report-dto';

export interface GetEmployeeDistributionReport$Params {

/**
 * Date de référence
 */
  referenceDate: string;
}

export function getEmployeeDistributionReport(http: HttpClient, rootUrl: string, params: GetEmployeeDistributionReport$Params, context?: HttpContext): Observable<StrictHttpResponse<EmployeeDistributionReportDto>> {
  const rb = new RequestBuilder(rootUrl, getEmployeeDistributionReport.PATH, 'get');
  if (params) {
    rb.query('referenceDate', params.referenceDate, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<EmployeeDistributionReportDto>;
    })
  );
}

getEmployeeDistributionReport.PATH = '/reports/distribution/date';
