/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AbsenteeismReportDto } from '../../models/absenteeism-report-dto';

export interface GetAbsenteeismReportForPeriod$Params {

/**
 * Date de début de la période
 */
  startDate: string;

/**
 * Date de fin de la période
 */
  endDate: string;
}

export function getAbsenteeismReportForPeriod(http: HttpClient, rootUrl: string, params: GetAbsenteeismReportForPeriod$Params, context?: HttpContext): Observable<StrictHttpResponse<AbsenteeismReportDto>> {
  const rb = new RequestBuilder(rootUrl, getAbsenteeismReportForPeriod.PATH, 'get');
  if (params) {
    rb.query('startDate', params.startDate, {});
    rb.query('endDate', params.endDate, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AbsenteeismReportDto>;
    })
  );
}

getAbsenteeismReportForPeriod.PATH = '/reports/absenteeism/period';
