/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { EmployeeDistributionReportDto } from '../../models/employee-distribution-report-dto';

export interface GetCurrentEmployeeDistributionReport$Params {
}

export function getCurrentEmployeeDistributionReport(http: HttpClient, rootUrl: string, params?: GetCurrentEmployeeDistributionReport$Params, context?: HttpContext): Observable<StrictHttpResponse<EmployeeDistributionReportDto>> {
  const rb = new RequestBuilder(rootUrl, getCurrentEmployeeDistributionReport.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<EmployeeDistributionReportDto>;
    })
  );
}

getCurrentEmployeeDistributionReport.PATH = '/reports/distribution';
