/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AbsenteeismReportDto } from '../../models/absenteeism-report-dto';

export interface GetAbsenteeismReport$Params {

/**
 * Année pour le rapport
 */
  year: number;
}

export function getAbsenteeismReport(http: HttpClient, rootUrl: string, params: GetAbsenteeismReport$Params, context?: HttpContext): Observable<StrictHttpResponse<AbsenteeismReportDto>> {
  const rb = new RequestBuilder(rootUrl, getAbsenteeismReport.PATH, 'get');
  if (params) {
    rb.path('year', params.year, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AbsenteeismReportDto>;
    })
  );
}

getAbsenteeismReport.PATH = '/reports/absenteeism/{year}';
