/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { LeavePolicyCreateDto } from '../../models/leave-policy-create-dto';
import { LeavePolicyDto } from '../../models/leave-policy-dto';

export interface CreateLeavePolicy$Params {
      body: LeavePolicyCreateDto
}

export function createLeavePolicy(http: HttpClient, rootUrl: string, params: CreateLeavePolicy$Params, context?: HttpContext): Observable<StrictHttpResponse<LeavePolicyDto>> {
  const rb = new RequestBuilder(rootUrl, createLeavePolicy.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<LeavePolicyDto>;
    })
  );
}

createLeavePolicy.PATH = '/leave-policies';
