/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { LeavePolicyDto } from '../../models/leave-policy-dto';

export interface DuplicateLeavePolicies$Params {

/**
 * Année source
 */
  sourceYear: number;

/**
 * Année cible
 */
  targetYear: number;
}

export function duplicateLeavePolicies(http: HttpClient, rootUrl: string, params: DuplicateLeavePolicies$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<LeavePolicyDto>>> {
  const rb = new RequestBuilder(rootUrl, duplicateLeavePolicies.PATH, 'post');
  if (params) {
    rb.query('sourceYear', params.sourceYear, {});
    rb.query('targetYear', params.targetYear, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<LeavePolicyDto>>;
    })
  );
}

duplicateLeavePolicies.PATH = '/leave-policies/duplicate';
