/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { LeavePolicyDto } from '../../models/leave-policy-dto';

export interface GetLeavePolicyByTypeAndYear$Params {

/**
 * Type de congés
 */
  leaveType: 'ANNUAL_LEAVE' | 'SICK_LEAVE' | 'MATERNITY_LEAVE' | 'PATERNITY_LEAVE' | 'UNPAID_LEAVE' | 'BEREAVEMENT_LEAVE' | 'MARRIAGE_LEAVE' | 'TRAINING_LEAVE' | 'SABBATICAL_LEAVE' | 'OTHER';

/**
 * Année
 */
  year: number;
}

export function getLeavePolicyByTypeAndYear(http: HttpClient, rootUrl: string, params: GetLeavePolicyByTypeAndYear$Params, context?: HttpContext): Observable<StrictHttpResponse<LeavePolicyDto>> {
  const rb = new RequestBuilder(rootUrl, getLeavePolicyByTypeAndYear.PATH, 'get');
  if (params) {
    rb.path('leaveType', params.leaveType, {});
    rb.path('year', params.year, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<LeavePolicyDto>;
    })
  );
}

getLeavePolicyByTypeAndYear.PATH = '/leave-policies/type/{leaveType}/year/{year}';
