/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { LeavePolicyDto } from '../../models/leave-policy-dto';

export interface GetAllLeavePolicies$Params {
}

export function getAllLeavePolicies(http: HttpClient, rootUrl: string, params?: GetAllLeavePolicies$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<LeavePolicyDto>>> {
  const rb = new RequestBuilder(rootUrl, getAllLeavePolicies.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<LeavePolicyDto>>;
    })
  );
}

getAllLeavePolicies.PATH = '/leave-policies';
