/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { LeavePolicyCreateDto } from '../../models/leave-policy-create-dto';
import { LeavePolicyDto } from '../../models/leave-policy-dto';

export interface UpdateLeavePolicy$Params {

/**
 * ID de la politique de congés
 */
  id: number;
      body: LeavePolicyCreateDto
}

export function updateLeavePolicy(http: HttpClient, rootUrl: string, params: UpdateLeavePolicy$Params, context?: HttpContext): Observable<StrictHttpResponse<LeavePolicyDto>> {
  const rb = new RequestBuilder(rootUrl, updateLeavePolicy.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<LeavePolicyDto>;
    })
  );
}

updateLeavePolicy.PATH = '/leave-policies/{id}';
