/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DepartmentEmployeeStatsDto } from '../../models/department-employee-stats-dto';

export interface GetEmployeeStatsByDepartment$Params {
}

export function getEmployeeStatsByDepartment(http: HttpClient, rootUrl: string, params?: GetEmployeeStatsByDepartment$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<DepartmentEmployeeStatsDto>>> {
  const rb = new RequestBuilder(rootUrl, getEmployeeStatsByDepartment.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<DepartmentEmployeeStatsDto>>;
    })
  );
}

getEmployeeStatsByDepartment.PATH = '/employees/stats';
