/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Pageable } from '../../models/pageable';
import { PageEmployeeDto } from '../../models/page-employee-dto';

export interface GetAllEmployees$Params {
  arg0: Pageable;
}

export function getAllEmployees(http: HttpClient, rootUrl: string, params: GetAllEmployees$Params, context?: HttpContext): Observable<StrictHttpResponse<PageEmployeeDto>> {
  const rb = new RequestBuilder(rootUrl, getAllEmployees.PATH, 'get');
  if (params) {
    rb.query('arg0', params.arg0, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageEmployeeDto>;
    })
  );
}

getAllEmployees.PATH = '/employees';
