/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Pageable } from '../../models/pageable';
import { PageEmployeeDto } from '../../models/page-employee-dto';

export interface SearchEmployees$Params {
  keyword?: string;
  status?: 'ACTIVE' | 'INACTIVE' | 'ON_LEAVE' | 'TERMINATED';
  departmentId?: number;
  pageable: Pageable;
}

export function searchEmployees(http: HttpClient, rootUrl: string, params: SearchEmployees$Params, context?: HttpContext): Observable<StrictHttpResponse<PageEmployeeDto>> {
  const rb = new RequestBuilder(rootUrl, searchEmployees.PATH, 'get');
  if (params) {
    rb.query('keyword', params.keyword, {});
    rb.query('status', params.status, {});
    rb.query('departmentId', params.departmentId, {});
    rb.query('pageable', params.pageable, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageEmployeeDto>;
    })
  );
}

searchEmployees.PATH = '/employees/search';
