/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { cancelLeave } from '../fn/conges/cancel-leave';
import { CancelLeave$Params } from '../fn/conges/cancel-leave';
import { checkOverlappingLeave } from '../fn/conges/check-overlapping-leave';
import { CheckOverlappingLeave$Params } from '../fn/conges/check-overlapping-leave';
import { createLeave } from '../fn/conges/create-leave';
import { CreateLeave$Params } from '../fn/conges/create-leave';
import { getAllLeaves } from '../fn/conges/get-all-leaves';
import { GetAllLeaves$Params } from '../fn/conges/get-all-leaves';
import { getEmployeeLeaves } from '../fn/conges/get-employee-leaves';
import { GetEmployeeLeaves$Params } from '../fn/conges/get-employee-leaves';
import { getEmployeeLeaveSummary } from '../fn/conges/get-employee-leave-summary';
import { GetEmployeeLeaveSummary$Params } from '../fn/conges/get-employee-leave-summary';
import { getLeaveById } from '../fn/conges/get-leave-by-id';
import { GetLeaveById$Params } from '../fn/conges/get-leave-by-id';
import { getLeavesByDepartmentInPeriod } from '../fn/conges/get-leaves-by-department-in-period';
import { GetLeavesByDepartmentInPeriod$Params } from '../fn/conges/get-leaves-by-department-in-period';
import { getLeavesInPeriod } from '../fn/conges/get-leaves-in-period';
import { GetLeavesInPeriod$Params } from '../fn/conges/get-leaves-in-period';
import { getPendingLeavesByManager } from '../fn/conges/get-pending-leaves-by-manager';
import { GetPendingLeavesByManager$Params } from '../fn/conges/get-pending-leaves-by-manager';
import { LeaveDto } from '../models/leave-dto';
import { LeaveEmployeeSummaryDto } from '../models/leave-employee-summary-dto';
import { PageLeaveDto } from '../models/page-leave-dto';
import { searchLeaves } from '../fn/conges/search-leaves';
import { SearchLeaves$Params } from '../fn/conges/search-leaves';
import { updateLeave } from '../fn/conges/update-leave';
import { UpdateLeave$Params } from '../fn/conges/update-leave';
import { updateLeaveStatus } from '../fn/conges/update-leave-status';
import { UpdateLeaveStatus$Params } from '../fn/conges/update-leave-status';


/**
 * API pour la gestion des demandes de congés
 */
@Injectable({ providedIn: 'root' })
export class CongesService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getLeaveById()` */
  static readonly GetLeaveByIdPath = '/leaves/{id}';

  /**
   * Récupérer une demande de congés par ID.
   *
   * Retourne une demande de congés spécifique par son ID
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getLeaveById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getLeaveById$Response(params: GetLeaveById$Params, context?: HttpContext): Observable<StrictHttpResponse<LeaveDto>> {
    return getLeaveById(this.http, this.rootUrl, params, context);
  }

  /**
   * Récupérer une demande de congés par ID.
   *
   * Retourne une demande de congés spécifique par son ID
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getLeaveById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getLeaveById(params: GetLeaveById$Params, context?: HttpContext): Observable<LeaveDto> {
    return this.getLeaveById$Response(params, context).pipe(
      map((r: StrictHttpResponse<LeaveDto>): LeaveDto => r.body)
    );
  }

  /** Path part for operation `updateLeave()` */
  static readonly UpdateLeavePath = '/leaves/{id}';

  /**
   * Mettre à jour une demande de congés.
   *
   * Met à jour une demande de congés existante
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateLeave()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateLeave$Response(params: UpdateLeave$Params, context?: HttpContext): Observable<StrictHttpResponse<LeaveDto>> {
    return updateLeave(this.http, this.rootUrl, params, context);
  }

  /**
   * Mettre à jour une demande de congés.
   *
   * Met à jour une demande de congés existante
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateLeave$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateLeave(params: UpdateLeave$Params, context?: HttpContext): Observable<LeaveDto> {
    return this.updateLeave$Response(params, context).pipe(
      map((r: StrictHttpResponse<LeaveDto>): LeaveDto => r.body)
    );
  }

  /** Path part for operation `getAllLeaves()` */
  static readonly GetAllLeavesPath = '/leaves';

  /**
   * Récupérer toutes les demandes de congés.
   *
   * Retourne une liste paginée de toutes les demandes de congés
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllLeaves()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllLeaves$Response(params: GetAllLeaves$Params, context?: HttpContext): Observable<StrictHttpResponse<PageLeaveDto>> {
    return getAllLeaves(this.http, this.rootUrl, params, context);
  }

  /**
   * Récupérer toutes les demandes de congés.
   *
   * Retourne une liste paginée de toutes les demandes de congés
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllLeaves$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllLeaves(params: GetAllLeaves$Params, context?: HttpContext): Observable<PageLeaveDto> {
    return this.getAllLeaves$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageLeaveDto>): PageLeaveDto => r.body)
    );
  }

  /** Path part for operation `createLeave()` */
  static readonly CreateLeavePath = '/leaves';

  /**
   * Créer une nouvelle demande de congés.
   *
   * Crée une nouvelle demande de congés et retourne la demande créée
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createLeave()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createLeave$Response(params: CreateLeave$Params, context?: HttpContext): Observable<StrictHttpResponse<LeaveDto>> {
    return createLeave(this.http, this.rootUrl, params, context);
  }

  /**
   * Créer une nouvelle demande de congés.
   *
   * Crée une nouvelle demande de congés et retourne la demande créée
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createLeave$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createLeave(params: CreateLeave$Params, context?: HttpContext): Observable<LeaveDto> {
    return this.createLeave$Response(params, context).pipe(
      map((r: StrictHttpResponse<LeaveDto>): LeaveDto => r.body)
    );
  }

  /** Path part for operation `cancelLeave()` */
  static readonly CancelLeavePath = '/leaves/{id}/cancel';

  /**
   * Annuler une demande de congés.
   *
   * Annule une demande de congés existante
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `cancelLeave()` instead.
   *
   * This method doesn't expect any request body.
   */
  cancelLeave$Response(params: CancelLeave$Params, context?: HttpContext): Observable<StrictHttpResponse<LeaveDto>> {
    return cancelLeave(this.http, this.rootUrl, params, context);
  }

  /**
   * Annuler une demande de congés.
   *
   * Annule une demande de congés existante
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `cancelLeave$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  cancelLeave(params: CancelLeave$Params, context?: HttpContext): Observable<LeaveDto> {
    return this.cancelLeave$Response(params, context).pipe(
      map((r: StrictHttpResponse<LeaveDto>): LeaveDto => r.body)
    );
  }

  /** Path part for operation `updateLeaveStatus()` */
  static readonly UpdateLeaveStatusPath = '/leaves/{id}/status';

  /**
   * Mettre à jour le statut d'une demande de congés.
   *
   * Approuve ou rejette une demande de congés
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateLeaveStatus()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateLeaveStatus$Response(params: UpdateLeaveStatus$Params, context?: HttpContext): Observable<StrictHttpResponse<LeaveDto>> {
    return updateLeaveStatus(this.http, this.rootUrl, params, context);
  }

  /**
   * Mettre à jour le statut d'une demande de congés.
   *
   * Approuve ou rejette une demande de congés
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateLeaveStatus$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateLeaveStatus(params: UpdateLeaveStatus$Params, context?: HttpContext): Observable<LeaveDto> {
    return this.updateLeaveStatus$Response(params, context).pipe(
      map((r: StrictHttpResponse<LeaveDto>): LeaveDto => r.body)
    );
  }

  /** Path part for operation `searchLeaves()` */
  static readonly SearchLeavesPath = '/leaves/search';

  /**
   * Rechercher des demandes de congés.
   *
   * Recherche des demandes de congés selon différents critères
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `searchLeaves()` instead.
   *
   * This method doesn't expect any request body.
   */
  searchLeaves$Response(params: SearchLeaves$Params, context?: HttpContext): Observable<StrictHttpResponse<PageLeaveDto>> {
    return searchLeaves(this.http, this.rootUrl, params, context);
  }

  /**
   * Rechercher des demandes de congés.
   *
   * Recherche des demandes de congés selon différents critères
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `searchLeaves$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  searchLeaves(params: SearchLeaves$Params, context?: HttpContext): Observable<PageLeaveDto> {
    return this.searchLeaves$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageLeaveDto>): PageLeaveDto => r.body)
    );
  }

  /** Path part for operation `getLeavesInPeriod()` */
  static readonly GetLeavesInPeriodPath = '/leaves/period';

  /**
   * Récupérer les congés pour une période donnée.
   *
   * Retourne les congés approuvés pour une période spécifique
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getLeavesInPeriod()` instead.
   *
   * This method doesn't expect any request body.
   */
  getLeavesInPeriod$Response(params: GetLeavesInPeriod$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<LeaveDto>>> {
    return getLeavesInPeriod(this.http, this.rootUrl, params, context);
  }

  /**
   * Récupérer les congés pour une période donnée.
   *
   * Retourne les congés approuvés pour une période spécifique
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getLeavesInPeriod$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getLeavesInPeriod(params: GetLeavesInPeriod$Params, context?: HttpContext): Observable<Array<LeaveDto>> {
    return this.getLeavesInPeriod$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<LeaveDto>>): Array<LeaveDto> => r.body)
    );
  }

  /** Path part for operation `getPendingLeavesByManager()` */
  static readonly GetPendingLeavesByManagerPath = '/leaves/pending/manager/{managerId}';

  /**
   * Récupérer les demandes de congés en attente pour un manager.
   *
   * Retourne les demandes de congés en attente d'approbation par un manager spécifique
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getPendingLeavesByManager()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPendingLeavesByManager$Response(params: GetPendingLeavesByManager$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<LeaveDto>>> {
    return getPendingLeavesByManager(this.http, this.rootUrl, params, context);
  }

  /**
   * Récupérer les demandes de congés en attente pour un manager.
   *
   * Retourne les demandes de congés en attente d'approbation par un manager spécifique
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getPendingLeavesByManager$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPendingLeavesByManager(params: GetPendingLeavesByManager$Params, context?: HttpContext): Observable<Array<LeaveDto>> {
    return this.getPendingLeavesByManager$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<LeaveDto>>): Array<LeaveDto> => r.body)
    );
  }

  /** Path part for operation `checkOverlappingLeave()` */
  static readonly CheckOverlappingLeavePath = '/leaves/overlap';

  /**
   * Vérifier le chevauchement de congés.
   *
   * Vérifie si un employé a des congés qui se chevauchent avec une période donnée
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `checkOverlappingLeave()` instead.
   *
   * This method doesn't expect any request body.
   */
  checkOverlappingLeave$Response(params: CheckOverlappingLeave$Params, context?: HttpContext): Observable<StrictHttpResponse<boolean>> {
    return checkOverlappingLeave(this.http, this.rootUrl, params, context);
  }

  /**
   * Vérifier le chevauchement de congés.
   *
   * Vérifie si un employé a des congés qui se chevauchent avec une période donnée
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `checkOverlappingLeave$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  checkOverlappingLeave(params: CheckOverlappingLeave$Params, context?: HttpContext): Observable<boolean> {
    return this.checkOverlappingLeave$Response(params, context).pipe(
      map((r: StrictHttpResponse<boolean>): boolean => r.body)
    );
  }

  /** Path part for operation `getEmployeeLeaves()` */
  static readonly GetEmployeeLeavesPath = '/leaves/employee/{employeeId}';

  /**
   * Récupérer les demandes de congés d'un employé.
   *
   * Retourne les demandes de congés d'un employé spécifique
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getEmployeeLeaves()` instead.
   *
   * This method doesn't expect any request body.
   */
  getEmployeeLeaves$Response(params: GetEmployeeLeaves$Params, context?: HttpContext): Observable<StrictHttpResponse<PageLeaveDto>> {
    return getEmployeeLeaves(this.http, this.rootUrl, params, context);
  }

  /**
   * Récupérer les demandes de congés d'un employé.
   *
   * Retourne les demandes de congés d'un employé spécifique
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getEmployeeLeaves$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getEmployeeLeaves(params: GetEmployeeLeaves$Params, context?: HttpContext): Observable<PageLeaveDto> {
    return this.getEmployeeLeaves$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageLeaveDto>): PageLeaveDto => r.body)
    );
  }

  /** Path part for operation `getEmployeeLeaveSummary()` */
  static readonly GetEmployeeLeaveSummaryPath = '/leaves/employee/{employeeId}/summary';

  /**
   * Récupérer un résumé des congés pour un employé.
   *
   * Retourne un résumé des congés d'un employé spécifique
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getEmployeeLeaveSummary()` instead.
   *
   * This method doesn't expect any request body.
   */
  getEmployeeLeaveSummary$Response(params: GetEmployeeLeaveSummary$Params, context?: HttpContext): Observable<StrictHttpResponse<LeaveEmployeeSummaryDto>> {
    return getEmployeeLeaveSummary(this.http, this.rootUrl, params, context);
  }

  /**
   * Récupérer un résumé des congés pour un employé.
   *
   * Retourne un résumé des congés d'un employé spécifique
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getEmployeeLeaveSummary$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getEmployeeLeaveSummary(params: GetEmployeeLeaveSummary$Params, context?: HttpContext): Observable<LeaveEmployeeSummaryDto> {
    return this.getEmployeeLeaveSummary$Response(params, context).pipe(
      map((r: StrictHttpResponse<LeaveEmployeeSummaryDto>): LeaveEmployeeSummaryDto => r.body)
    );
  }

  /** Path part for operation `getLeavesByDepartmentInPeriod()` */
  static readonly GetLeavesByDepartmentInPeriodPath = '/leaves/department/{departmentId}/period';

  /**
   * Récupérer les congés d'un département pour une période donnée.
   *
   * Retourne les congés approuvés d'un département pour une période spécifique
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getLeavesByDepartmentInPeriod()` instead.
   *
   * This method doesn't expect any request body.
   */
  getLeavesByDepartmentInPeriod$Response(params: GetLeavesByDepartmentInPeriod$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<LeaveDto>>> {
    return getLeavesByDepartmentInPeriod(this.http, this.rootUrl, params, context);
  }

  /**
   * Récupérer les congés d'un département pour une période donnée.
   *
   * Retourne les congés approuvés d'un département pour une période spécifique
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getLeavesByDepartmentInPeriod$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getLeavesByDepartmentInPeriod(params: GetLeavesByDepartmentInPeriod$Params, context?: HttpContext): Observable<Array<LeaveDto>> {
    return this.getLeavesByDepartmentInPeriod$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<LeaveDto>>): Array<LeaveDto> => r.body)
    );
  }

}
