/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { ContractDto } from '../models/contract-dto';
import { createContract } from '../fn/contrats/create-contract';
import { CreateContract$Params } from '../fn/contrats/create-contract';
import { deleteContract } from '../fn/contrats/delete-contract';
import { DeleteContract$Params } from '../fn/contrats/delete-contract';
import { generateContractDocument } from '../fn/contrats/generate-contract-document';
import { GenerateContractDocument$Params } from '../fn/contrats/generate-contract-document';
import { getActiveEmployeeContract } from '../fn/contrats/get-active-employee-contract';
import { GetActiveEmployeeContract$Params } from '../fn/contrats/get-active-employee-contract';
import { getAllContracts } from '../fn/contrats/get-all-contracts';
import { GetAllContracts$Params } from '../fn/contrats/get-all-contracts';
import { getContractById } from '../fn/contrats/get-contract-by-id';
import { GetContractById$Params } from '../fn/contrats/get-contract-by-id';
import { getContractsByStatus } from '../fn/contrats/get-contracts-by-status';
import { GetContractsByStatus$Params } from '../fn/contrats/get-contracts-by-status';
import { getContractsByType } from '../fn/contrats/get-contracts-by-type';
import { GetContractsByType$Params } from '../fn/contrats/get-contracts-by-type';
import { getEmployeeContracts } from '../fn/contrats/get-employee-contracts';
import { GetEmployeeContracts$Params } from '../fn/contrats/get-employee-contracts';
import { getExpiringContracts } from '../fn/contrats/get-expiring-contracts';
import { GetExpiringContracts$Params } from '../fn/contrats/get-expiring-contracts';
import { PageContractDto } from '../models/page-contract-dto';
import { searchContracts } from '../fn/contrats/search-contracts';
import { SearchContracts$Params } from '../fn/contrats/search-contracts';
import { updateContract } from '../fn/contrats/update-contract';
import { UpdateContract$Params } from '../fn/contrats/update-contract';
import { updateContractStatus } from '../fn/contrats/update-contract-status';
import { UpdateContractStatus$Params } from '../fn/contrats/update-contract-status';


/**
 * API pour la gestion des contrats de travail
 */
@Injectable({ providedIn: 'root' })
export class ContratsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getContractById()` */
  static readonly GetContractByIdPath = '/contracts/{id}';

  /**
   * Récupérer un contrat par ID.
   *
   * Retourne un contrat spécifique par son identifiant
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getContractById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getContractById$Response(params?: GetContractById$Params, context?: HttpContext): Observable<StrictHttpResponse<ContractDto>> {
    return getContractById(this.http, this.rootUrl, params, context);
  }

  /**
   * Récupérer un contrat par ID.
   *
   * Retourne un contrat spécifique par son identifiant
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getContractById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getContractById(params?: GetContractById$Params, context?: HttpContext): Observable<ContractDto> {
    return this.getContractById$Response(params, context).pipe(
      map((r: StrictHttpResponse<ContractDto>): ContractDto => r.body)
    );
  }

  /** Path part for operation `updateContract()` */
  static readonly UpdateContractPath = '/contracts/{id}';

  /**
   * Mettre à jour un contrat.
   *
   * Met à jour un contrat existant
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateContract()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateContract$Response(params: UpdateContract$Params, context?: HttpContext): Observable<StrictHttpResponse<ContractDto>> {
    return updateContract(this.http, this.rootUrl, params, context);
  }

  /**
   * Mettre à jour un contrat.
   *
   * Met à jour un contrat existant
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateContract$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateContract(params: UpdateContract$Params, context?: HttpContext): Observable<ContractDto> {
    return this.updateContract$Response(params, context).pipe(
      map((r: StrictHttpResponse<ContractDto>): ContractDto => r.body)
    );
  }

  /** Path part for operation `deleteContract()` */
  static readonly DeleteContractPath = '/contracts/{id}';

  /**
   * Supprimer un contrat.
   *
   * Supprime un contrat du système
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteContract()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteContract$Response(params?: DeleteContract$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return deleteContract(this.http, this.rootUrl, params, context);
  }

  /**
   * Supprimer un contrat.
   *
   * Supprime un contrat du système
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteContract$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteContract(params?: DeleteContract$Params, context?: HttpContext): Observable<void> {
    return this.deleteContract$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getAllContracts()` */
  static readonly GetAllContractsPath = '/contracts';

  /**
   * Récupérer tous les contrats.
   *
   * Retourne une liste paginée de tous les contrats
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllContracts()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllContracts$Response(params: GetAllContracts$Params, context?: HttpContext): Observable<StrictHttpResponse<PageContractDto>> {
    return getAllContracts(this.http, this.rootUrl, params, context);
  }

  /**
   * Récupérer tous les contrats.
   *
   * Retourne une liste paginée de tous les contrats
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllContracts$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllContracts(params: GetAllContracts$Params, context?: HttpContext): Observable<PageContractDto> {
    return this.getAllContracts$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageContractDto>): PageContractDto => r.body)
    );
  }

  /** Path part for operation `createContract()` */
  static readonly CreateContractPath = '/contracts';

  /**
   * Créer un nouveau contrat.
   *
   * Crée un nouveau contrat dans le système
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createContract()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createContract$Response(params: CreateContract$Params, context?: HttpContext): Observable<StrictHttpResponse<ContractDto>> {
    return createContract(this.http, this.rootUrl, params, context);
  }

  /**
   * Créer un nouveau contrat.
   *
   * Crée un nouveau contrat dans le système
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createContract$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createContract(params: CreateContract$Params, context?: HttpContext): Observable<ContractDto> {
    return this.createContract$Response(params, context).pipe(
      map((r: StrictHttpResponse<ContractDto>): ContractDto => r.body)
    );
  }

  /** Path part for operation `updateContractStatus()` */
  static readonly UpdateContractStatusPath = '/contracts/{id}/status';

  /**
   * Mettre à jour le statut d'un contrat.
   *
   * Change le statut d'un contrat existant
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateContractStatus()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateContractStatus$Response(params: UpdateContractStatus$Params, context?: HttpContext): Observable<StrictHttpResponse<ContractDto>> {
    return updateContractStatus(this.http, this.rootUrl, params, context);
  }

  /**
   * Mettre à jour le statut d'un contrat.
   *
   * Change le statut d'un contrat existant
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateContractStatus$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateContractStatus(params: UpdateContractStatus$Params, context?: HttpContext): Observable<ContractDto> {
    return this.updateContractStatus$Response(params, context).pipe(
      map((r: StrictHttpResponse<ContractDto>): ContractDto => r.body)
    );
  }

  /** Path part for operation `generateContractDocument()` */
  static readonly GenerateContractDocumentPath = '/contracts/{id}/document';

  /**
   * Générer un document de contrat.
   *
   * Génère un document Word basé sur un contrat
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `generateContractDocument()` instead.
   *
   * This method doesn't expect any request body.
   */
  generateContractDocument$Response(params?: GenerateContractDocument$Params, context?: HttpContext): Observable<StrictHttpResponse<Blob>> {
    return generateContractDocument(this.http, this.rootUrl, params, context);
  }

  /**
   * Générer un document de contrat.
   *
   * Génère un document Word basé sur un contrat
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `generateContractDocument$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  generateContractDocument(params?: GenerateContractDocument$Params, context?: HttpContext): Observable<Blob> {
    return this.generateContractDocument$Response(params, context).pipe(
      map((r: StrictHttpResponse<Blob>): Blob => r.body)
    );
  }

  /** Path part for operation `getContractsByType()` */
  static readonly GetContractsByTypePath = '/contracts/type/{type}';

  /**
   * Récupérer les contrats par type.
   *
   * Retourne tous les contrats d'un type spécifique
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getContractsByType()` instead.
   *
   * This method doesn't expect any request body.
   */
  getContractsByType$Response(params?: GetContractsByType$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ContractDto>>> {
    return getContractsByType(this.http, this.rootUrl, params, context);
  }

  /**
   * Récupérer les contrats par type.
   *
   * Retourne tous les contrats d'un type spécifique
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getContractsByType$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getContractsByType(params?: GetContractsByType$Params, context?: HttpContext): Observable<Array<ContractDto>> {
    return this.getContractsByType$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<ContractDto>>): Array<ContractDto> => r.body)
    );
  }

  /** Path part for operation `getContractsByStatus()` */
  static readonly GetContractsByStatusPath = '/contracts/status/{status}';

  /**
   * Récupérer les contrats par statut.
   *
   * Retourne tous les contrats ayant un statut spécifique
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getContractsByStatus()` instead.
   *
   * This method doesn't expect any request body.
   */
  getContractsByStatus$Response(params?: GetContractsByStatus$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ContractDto>>> {
    return getContractsByStatus(this.http, this.rootUrl, params, context);
  }

  /**
   * Récupérer les contrats par statut.
   *
   * Retourne tous les contrats ayant un statut spécifique
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getContractsByStatus$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getContractsByStatus(params?: GetContractsByStatus$Params, context?: HttpContext): Observable<Array<ContractDto>> {
    return this.getContractsByStatus$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<ContractDto>>): Array<ContractDto> => r.body)
    );
  }

  /** Path part for operation `searchContracts()` */
  static readonly SearchContractsPath = '/contracts/search';

  /**
   * Rechercher des contrats.
   *
   * Recherche des contrats selon plusieurs critères
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `searchContracts()` instead.
   *
   * This method doesn't expect any request body.
   */
  searchContracts$Response(params: SearchContracts$Params, context?: HttpContext): Observable<StrictHttpResponse<PageContractDto>> {
    return searchContracts(this.http, this.rootUrl, params, context);
  }

  /**
   * Rechercher des contrats.
   *
   * Recherche des contrats selon plusieurs critères
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `searchContracts$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  searchContracts(params: SearchContracts$Params, context?: HttpContext): Observable<PageContractDto> {
    return this.searchContracts$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageContractDto>): PageContractDto => r.body)
    );
  }

  /** Path part for operation `getExpiringContracts()` */
  static readonly GetExpiringContractsPath = '/contracts/expiring';

  /**
   * Récupérer les contrats qui expirent bientôt.
   *
   * Retourne les contrats qui expirent dans les prochains jours
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getExpiringContracts()` instead.
   *
   * This method doesn't expect any request body.
   */
  getExpiringContracts$Response(params?: GetExpiringContracts$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ContractDto>>> {
    return getExpiringContracts(this.http, this.rootUrl, params, context);
  }

  /**
   * Récupérer les contrats qui expirent bientôt.
   *
   * Retourne les contrats qui expirent dans les prochains jours
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getExpiringContracts$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getExpiringContracts(params?: GetExpiringContracts$Params, context?: HttpContext): Observable<Array<ContractDto>> {
    return this.getExpiringContracts$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<ContractDto>>): Array<ContractDto> => r.body)
    );
  }

  /** Path part for operation `getEmployeeContracts()` */
  static readonly GetEmployeeContractsPath = '/contracts/employee/{employeeId}';

  /**
   * Récupérer les contrats d'un employé.
   *
   * Retourne tous les contrats associés à un employé
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getEmployeeContracts()` instead.
   *
   * This method doesn't expect any request body.
   */
  getEmployeeContracts$Response(params?: GetEmployeeContracts$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ContractDto>>> {
    return getEmployeeContracts(this.http, this.rootUrl, params, context);
  }

  /**
   * Récupérer les contrats d'un employé.
   *
   * Retourne tous les contrats associés à un employé
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getEmployeeContracts$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getEmployeeContracts(params?: GetEmployeeContracts$Params, context?: HttpContext): Observable<Array<ContractDto>> {
    return this.getEmployeeContracts$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<ContractDto>>): Array<ContractDto> => r.body)
    );
  }

  /** Path part for operation `getActiveEmployeeContract()` */
  static readonly GetActiveEmployeeContractPath = '/contracts/employee/{employeeId}/active';

  /**
   * Récupérer le contrat actif d'un employé.
   *
   * Retourne le contrat actuellement actif d'un employé
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getActiveEmployeeContract()` instead.
   *
   * This method doesn't expect any request body.
   */
  getActiveEmployeeContract$Response(params?: GetActiveEmployeeContract$Params, context?: HttpContext): Observable<StrictHttpResponse<ContractDto>> {
    return getActiveEmployeeContract(this.http, this.rootUrl, params, context);
  }

  /**
   * Récupérer le contrat actif d'un employé.
   *
   * Retourne le contrat actuellement actif d'un employé
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getActiveEmployeeContract$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getActiveEmployeeContract(params?: GetActiveEmployeeContract$Params, context?: HttpContext): Observable<ContractDto> {
    return this.getActiveEmployeeContract$Response(params, context).pipe(
      map((r: StrictHttpResponse<ContractDto>): ContractDto => r.body)
    );
  }

}
