/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { createDepartement } from '../fn/departements/create-departement';
import { CreateDepartement$Params } from '../fn/departements/create-departement';
import { deleteDepartement } from '../fn/departements/delete-departement';
import { DeleteDepartement$Params } from '../fn/departements/delete-departement';
import { DepartementDto } from '../models/departement-dto';
import { DepartementTreeDto } from '../models/departement-tree-dto';
import { getAllDepartements } from '../fn/departements/get-all-departements';
import { GetAllDepartements$Params } from '../fn/departements/get-all-departements';
import { getDepartementById } from '../fn/departements/get-departement-by-id';
import { GetDepartementById$Params } from '../fn/departements/get-departement-by-id';
import { getDepartementTree } from '../fn/departements/get-departement-tree';
import { GetDepartementTree$Params } from '../fn/departements/get-departement-tree';
import { getEmployeesByDepartement } from '../fn/departements/get-employees-by-departement';
import { GetEmployeesByDepartement$Params } from '../fn/departements/get-employees-by-departement';
import { getSubDepartements } from '../fn/departements/get-sub-departements';
import { GetSubDepartements$Params } from '../fn/departements/get-sub-departements';
import { getTopLevelDepartements } from '../fn/departements/get-top-level-departements';
import { GetTopLevelDepartements$Params } from '../fn/departements/get-top-level-departements';
import { PageDepartementDto } from '../models/page-departement-dto';
import { PageEmployeeShortDto } from '../models/page-employee-short-dto';
import { searchDepartements } from '../fn/departements/search-departements';
import { SearchDepartements$Params } from '../fn/departements/search-departements';
import { updateDepartement } from '../fn/departements/update-departement';
import { UpdateDepartement$Params } from '../fn/departements/update-departement';
import { updateDepartementStatus } from '../fn/departements/update-departement-status';
import { UpdateDepartementStatus$Params } from '../fn/departements/update-departement-status';


/**
 * API pour la gestion des départements
 */
@Injectable({ providedIn: 'root' })
export class DepartementsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getDepartementById()` */
  static readonly GetDepartementByIdPath = '/departments/{id}';

  /**
   * Récupérer un département par ID.
   *
   * Retourne un département spécifique par son identifiant
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getDepartementById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getDepartementById$Response(params: GetDepartementById$Params, context?: HttpContext): Observable<StrictHttpResponse<DepartementDto>> {
    return getDepartementById(this.http, this.rootUrl, params, context);
  }

  /**
   * Récupérer un département par ID.
   *
   * Retourne un département spécifique par son identifiant
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getDepartementById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getDepartementById(params: GetDepartementById$Params, context?: HttpContext): Observable<DepartementDto> {
    return this.getDepartementById$Response(params, context).pipe(
      map((r: StrictHttpResponse<DepartementDto>): DepartementDto => r.body)
    );
  }

  /** Path part for operation `updateDepartement()` */
  static readonly UpdateDepartementPath = '/departments/{id}';

  /**
   * Mettre à jour un département.
   *
   * Met à jour un département existant
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateDepartement()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateDepartement$Response(params: UpdateDepartement$Params, context?: HttpContext): Observable<StrictHttpResponse<DepartementDto>> {
    return updateDepartement(this.http, this.rootUrl, params, context);
  }

  /**
   * Mettre à jour un département.
   *
   * Met à jour un département existant
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateDepartement$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateDepartement(params: UpdateDepartement$Params, context?: HttpContext): Observable<DepartementDto> {
    return this.updateDepartement$Response(params, context).pipe(
      map((r: StrictHttpResponse<DepartementDto>): DepartementDto => r.body)
    );
  }

  /** Path part for operation `deleteDepartement()` */
  static readonly DeleteDepartementPath = '/departments/{id}';

  /**
   * Supprimer un département.
   *
   * Supprime un département du système
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteDepartement()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteDepartement$Response(params: DeleteDepartement$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return deleteDepartement(this.http, this.rootUrl, params, context);
  }

  /**
   * Supprimer un département.
   *
   * Supprime un département du système
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteDepartement$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteDepartement(params: DeleteDepartement$Params, context?: HttpContext): Observable<void> {
    return this.deleteDepartement$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getAllDepartements()` */
  static readonly GetAllDepartementsPath = '/departments';

  /**
   * Récupérer tous les départements.
   *
   * Retourne une liste paginée de tous les départements
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllDepartements()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllDepartements$Response(params: GetAllDepartements$Params, context?: HttpContext): Observable<StrictHttpResponse<PageDepartementDto>> {
    return getAllDepartements(this.http, this.rootUrl, params, context);
  }

  /**
   * Récupérer tous les départements.
   *
   * Retourne une liste paginée de tous les départements
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllDepartements$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllDepartements(params: GetAllDepartements$Params, context?: HttpContext): Observable<PageDepartementDto> {
    return this.getAllDepartements$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageDepartementDto>): PageDepartementDto => r.body)
    );
  }

  /** Path part for operation `createDepartement()` */
  static readonly CreateDepartementPath = '/departments';

  /**
   * Créer un nouveau département.
   *
   * Crée un nouveau département dans le système
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createDepartement()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createDepartement$Response(params: CreateDepartement$Params, context?: HttpContext): Observable<StrictHttpResponse<DepartementDto>> {
    return createDepartement(this.http, this.rootUrl, params, context);
  }

  /**
   * Créer un nouveau département.
   *
   * Crée un nouveau département dans le système
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createDepartement$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createDepartement(params: CreateDepartement$Params, context?: HttpContext): Observable<DepartementDto> {
    return this.createDepartement$Response(params, context).pipe(
      map((r: StrictHttpResponse<DepartementDto>): DepartementDto => r.body)
    );
  }

  /** Path part for operation `updateDepartementStatus()` */
  static readonly UpdateDepartementStatusPath = '/departments/{id}/status';

  /**
   * Activer/désactiver un département.
   *
   * Change le statut d'un département (actif/inactif)
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateDepartementStatus()` instead.
   *
   * This method doesn't expect any request body.
   */
  updateDepartementStatus$Response(params: UpdateDepartementStatus$Params, context?: HttpContext): Observable<StrictHttpResponse<DepartementDto>> {
    return updateDepartementStatus(this.http, this.rootUrl, params, context);
  }

  /**
   * Activer/désactiver un département.
   *
   * Change le statut d'un département (actif/inactif)
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateDepartementStatus$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  updateDepartementStatus(params: UpdateDepartementStatus$Params, context?: HttpContext): Observable<DepartementDto> {
    return this.updateDepartementStatus$Response(params, context).pipe(
      map((r: StrictHttpResponse<DepartementDto>): DepartementDto => r.body)
    );
  }

  /** Path part for operation `getSubDepartements()` */
  static readonly GetSubDepartementsPath = '/departments/{id}/sub-departments';

  /**
   * Récupérer les sous-départements.
   *
   * Retourne les sous-départements d'un département parent
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getSubDepartements()` instead.
   *
   * This method doesn't expect any request body.
   */
  getSubDepartements$Response(params: GetSubDepartements$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<DepartementDto>>> {
    return getSubDepartements(this.http, this.rootUrl, params, context);
  }

  /**
   * Récupérer les sous-départements.
   *
   * Retourne les sous-départements d'un département parent
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getSubDepartements$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getSubDepartements(params: GetSubDepartements$Params, context?: HttpContext): Observable<Array<DepartementDto>> {
    return this.getSubDepartements$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<DepartementDto>>): Array<DepartementDto> => r.body)
    );
  }

  /** Path part for operation `getEmployeesByDepartement()` */
  static readonly GetEmployeesByDepartementPath = '/departments/{id}/employees';

  /**
   * Récupérer les employés d'un département.
   *
   * Retourne la liste des employés affectés à un département
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getEmployeesByDepartement()` instead.
   *
   * This method doesn't expect any request body.
   */
  getEmployeesByDepartement$Response(params: GetEmployeesByDepartement$Params, context?: HttpContext): Observable<StrictHttpResponse<PageEmployeeShortDto>> {
    return getEmployeesByDepartement(this.http, this.rootUrl, params, context);
  }

  /**
   * Récupérer les employés d'un département.
   *
   * Retourne la liste des employés affectés à un département
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getEmployeesByDepartement$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getEmployeesByDepartement(params: GetEmployeesByDepartement$Params, context?: HttpContext): Observable<PageEmployeeShortDto> {
    return this.getEmployeesByDepartement$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageEmployeeShortDto>): PageEmployeeShortDto => r.body)
    );
  }

  /** Path part for operation `getDepartementTree()` */
  static readonly GetDepartementTreePath = '/departments/tree';

  /**
   * Récupérer l'organigramme complet.
   *
   * Retourne la structure hiérarchique complète des départements
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getDepartementTree()` instead.
   *
   * This method doesn't expect any request body.
   */
  getDepartementTree$Response(params?: GetDepartementTree$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<DepartementTreeDto>>> {
    return getDepartementTree(this.http, this.rootUrl, params, context);
  }

  /**
   * Récupérer l'organigramme complet.
   *
   * Retourne la structure hiérarchique complète des départements
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getDepartementTree$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getDepartementTree(params?: GetDepartementTree$Params, context?: HttpContext): Observable<Array<DepartementTreeDto>> {
    return this.getDepartementTree$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<DepartementTreeDto>>): Array<DepartementTreeDto> => r.body)
    );
  }

  /** Path part for operation `getTopLevelDepartements()` */
  static readonly GetTopLevelDepartementsPath = '/departments/top-level';

  /**
   * Récupérer les départements de premier niveau.
   *
   * Retourne les départements sans parent
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getTopLevelDepartements()` instead.
   *
   * This method doesn't expect any request body.
   */
  getTopLevelDepartements$Response(params?: GetTopLevelDepartements$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<DepartementDto>>> {
    return getTopLevelDepartements(this.http, this.rootUrl, params, context);
  }

  /**
   * Récupérer les départements de premier niveau.
   *
   * Retourne les départements sans parent
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getTopLevelDepartements$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getTopLevelDepartements(params?: GetTopLevelDepartements$Params, context?: HttpContext): Observable<Array<DepartementDto>> {
    return this.getTopLevelDepartements$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<DepartementDto>>): Array<DepartementDto> => r.body)
    );
  }

  /** Path part for operation `searchDepartements()` */
  static readonly SearchDepartementsPath = '/departments/search';

  /**
   * Rechercher des départements.
   *
   * Recherche des départements par nom ou code
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `searchDepartements()` instead.
   *
   * This method doesn't expect any request body.
   */
  searchDepartements$Response(params?: SearchDepartements$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<DepartementDto>>> {
    return searchDepartements(this.http, this.rootUrl, params, context);
  }

  /**
   * Rechercher des départements.
   *
   * Recherche des départements par nom ou code
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `searchDepartements$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  searchDepartements(params?: SearchDepartements$Params, context?: HttpContext): Observable<Array<DepartementDto>> {
    return this.searchDepartements$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<DepartementDto>>): Array<DepartementDto> => r.body)
    );
  }

}
