/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { deleteDocument } from '../fn/document-management/delete-document';
import { DeleteDocument$Params } from '../fn/document-management/delete-document';
import { DocumentDto } from '../models/document-dto';
import { DocumentShortDto } from '../models/document-short-dto';
import { getAllDocuments } from '../fn/document-management/get-all-documents';
import { GetAllDocuments$Params } from '../fn/document-management/get-all-documents';
import { getAllowedMimeTypes } from '../fn/document-management/get-allowed-mime-types';
import { GetAllowedMimeTypes$Params } from '../fn/document-management/get-allowed-mime-types';
import { getContractDocuments } from '../fn/document-management/get-contract-documents';
import { GetContractDocuments$Params } from '../fn/document-management/get-contract-documents';
import { getDocumentById } from '../fn/document-management/get-document-by-id';
import { GetDocumentById$Params } from '../fn/document-management/get-document-by-id';
import { getDocumentContent } from '../fn/document-management/get-document-content';
import { GetDocumentContent$Params } from '../fn/document-management/get-document-content';
import { getDocumentsByType } from '../fn/document-management/get-documents-by-type';
import { GetDocumentsByType$Params } from '../fn/document-management/get-documents-by-type';
import { getEmployeeDocumentContent } from '../fn/document-management/get-employee-document-content';
import { GetEmployeeDocumentContent$Params } from '../fn/document-management/get-employee-document-content';
import { getEmployeeDocuments } from '../fn/document-management/get-employee-documents';
import { GetEmployeeDocuments$Params } from '../fn/document-management/get-employee-documents';
import { PageDocumentShortDto } from '../models/page-document-short-dto';
import { searchDocuments } from '../fn/document-management/search-documents';
import { SearchDocuments$Params } from '../fn/document-management/search-documents';
import { updateDocument } from '../fn/document-management/update-document';
import { UpdateDocument$Params } from '../fn/document-management/update-document';
import { uploadContractDocument } from '../fn/document-management/upload-contract-document';
import { UploadContractDocument$Params } from '../fn/document-management/upload-contract-document';
import { uploadEmployeeDocument } from '../fn/document-management/upload-employee-document';
import { UploadEmployeeDocument$Params } from '../fn/document-management/upload-employee-document';


/**
 * API pour la gestion des documents dans le système RH
 */
@Injectable({ providedIn: 'root' })
export class DocumentManagementService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getDocumentById()` */
  static readonly GetDocumentByIdPath = '/documents/{id}';

  /**
   * Récupérer un document par ID.
   *
   * Retourne un document spécifique par son identifiant
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getDocumentById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getDocumentById$Response(params: GetDocumentById$Params, context?: HttpContext): Observable<StrictHttpResponse<DocumentDto>> {
    return getDocumentById(this.http, this.rootUrl, params, context);
  }

  /**
   * Récupérer un document par ID.
   *
   * Retourne un document spécifique par son identifiant
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getDocumentById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getDocumentById(params: GetDocumentById$Params, context?: HttpContext): Observable<DocumentDto> {
    return this.getDocumentById$Response(params, context).pipe(
      map((r: StrictHttpResponse<DocumentDto>): DocumentDto => r.body)
    );
  }

  /** Path part for operation `updateDocument()` */
  static readonly UpdateDocumentPath = '/documents/{id}';

  /**
   * Mettre à jour un document.
   *
   * Met à jour les métadonnées d'un document existant
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateDocument()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateDocument$Response(params: UpdateDocument$Params, context?: HttpContext): Observable<StrictHttpResponse<DocumentDto>> {
    return updateDocument(this.http, this.rootUrl, params, context);
  }

  /**
   * Mettre à jour un document.
   *
   * Met à jour les métadonnées d'un document existant
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateDocument$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateDocument(params: UpdateDocument$Params, context?: HttpContext): Observable<DocumentDto> {
    return this.updateDocument$Response(params, context).pipe(
      map((r: StrictHttpResponse<DocumentDto>): DocumentDto => r.body)
    );
  }

  /** Path part for operation `deleteDocument()` */
  static readonly DeleteDocumentPath = '/documents/{id}';

  /**
   * Supprimer un document.
   *
   * Supprime un document du système
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteDocument()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteDocument$Response(params: DeleteDocument$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return deleteDocument(this.http, this.rootUrl, params, context);
  }

  /**
   * Supprimer un document.
   *
   * Supprime un document du système
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteDocument$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteDocument(params: DeleteDocument$Params, context?: HttpContext): Observable<void> {
    return this.deleteDocument$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getEmployeeDocuments()` */
  static readonly GetEmployeeDocumentsPath = '/documents/employees/{employeeId}';

  /**
   * Récupérer les documents d'un employé.
   *
   * Retourne tous les documents associés à un employé
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getEmployeeDocuments()` instead.
   *
   * This method doesn't expect any request body.
   */
  getEmployeeDocuments$Response(params: GetEmployeeDocuments$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<DocumentShortDto>>> {
    return getEmployeeDocuments(this.http, this.rootUrl, params, context);
  }

  /**
   * Récupérer les documents d'un employé.
   *
   * Retourne tous les documents associés à un employé
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getEmployeeDocuments$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getEmployeeDocuments(params: GetEmployeeDocuments$Params, context?: HttpContext): Observable<Array<DocumentShortDto>> {
    return this.getEmployeeDocuments$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<DocumentShortDto>>): Array<DocumentShortDto> => r.body)
    );
  }

  /** Path part for operation `uploadEmployeeDocument()` */
  static readonly UploadEmployeeDocumentPath = '/documents/employees/{employeeId}';

  /**
   * Uploader un document pour un employé.
   *
   * Télécharge un nouveau document et l'associe à un employé
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `uploadEmployeeDocument()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  uploadEmployeeDocument$Response(params: UploadEmployeeDocument$Params, context?: HttpContext): Observable<StrictHttpResponse<DocumentDto>> {
    return uploadEmployeeDocument(this.http, this.rootUrl, params, context);
  }

  /**
   * Uploader un document pour un employé.
   *
   * Télécharge un nouveau document et l'associe à un employé
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `uploadEmployeeDocument$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  uploadEmployeeDocument(params: UploadEmployeeDocument$Params, context?: HttpContext): Observable<DocumentDto> {
    return this.uploadEmployeeDocument$Response(params, context).pipe(
      map((r: StrictHttpResponse<DocumentDto>): DocumentDto => r.body)
    );
  }

  /** Path part for operation `getContractDocuments()` */
  static readonly GetContractDocumentsPath = '/documents/contracts/{contractId}';

  /**
   * Récupérer les documents d'un contrat.
   *
   * Retourne tous les documents associés à un contrat
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getContractDocuments()` instead.
   *
   * This method doesn't expect any request body.
   */
  getContractDocuments$Response(params: GetContractDocuments$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<DocumentShortDto>>> {
    return getContractDocuments(this.http, this.rootUrl, params, context);
  }

  /**
   * Récupérer les documents d'un contrat.
   *
   * Retourne tous les documents associés à un contrat
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getContractDocuments$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getContractDocuments(params: GetContractDocuments$Params, context?: HttpContext): Observable<Array<DocumentShortDto>> {
    return this.getContractDocuments$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<DocumentShortDto>>): Array<DocumentShortDto> => r.body)
    );
  }

  /** Path part for operation `uploadContractDocument()` */
  static readonly UploadContractDocumentPath = '/documents/contracts/{contractId}';

  /**
   * Uploader un document pour un contrat.
   *
   * Télécharge un nouveau document et l'associe à un contrat
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `uploadContractDocument()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  uploadContractDocument$Response(params: UploadContractDocument$Params, context?: HttpContext): Observable<StrictHttpResponse<DocumentDto>> {
    return uploadContractDocument(this.http, this.rootUrl, params, context);
  }

  /**
   * Uploader un document pour un contrat.
   *
   * Télécharge un nouveau document et l'associe à un contrat
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `uploadContractDocument$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  uploadContractDocument(params: UploadContractDocument$Params, context?: HttpContext): Observable<DocumentDto> {
    return this.uploadContractDocument$Response(params, context).pipe(
      map((r: StrictHttpResponse<DocumentDto>): DocumentDto => r.body)
    );
  }

  /** Path part for operation `getAllDocuments()` */
  static readonly GetAllDocumentsPath = '/documents';

  /**
   * Récupérer tous les documents.
   *
   * Retourne une liste paginée de tous les documents
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllDocuments()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllDocuments$Response(params: GetAllDocuments$Params, context?: HttpContext): Observable<StrictHttpResponse<PageDocumentShortDto>> {
    return getAllDocuments(this.http, this.rootUrl, params, context);
  }

  /**
   * Récupérer tous les documents.
   *
   * Retourne une liste paginée de tous les documents
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllDocuments$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllDocuments(params: GetAllDocuments$Params, context?: HttpContext): Observable<PageDocumentShortDto> {
    return this.getAllDocuments$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageDocumentShortDto>): PageDocumentShortDto => r.body)
    );
  }

  /** Path part for operation `getDocumentContent()` */
  static readonly GetDocumentContentPath = '/documents/{id}/content';

  /**
   * Télécharger le contenu d'un document.
   *
   * Télécharge le fichier associé à un document
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getDocumentContent()` instead.
   *
   * This method doesn't expect any request body.
   */
  getDocumentContent$Response(params: GetDocumentContent$Params, context?: HttpContext): Observable<StrictHttpResponse<Blob>> {
    return getDocumentContent(this.http, this.rootUrl, params, context);
  }

  /**
   * Télécharger le contenu d'un document.
   *
   * Télécharge le fichier associé à un document
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getDocumentContent$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getDocumentContent(params: GetDocumentContent$Params, context?: HttpContext): Observable<Blob> {
    return this.getDocumentContent$Response(params, context).pipe(
      map((r: StrictHttpResponse<Blob>): Blob => r.body)
    );
  }

  /** Path part for operation `getDocumentsByType()` */
  static readonly GetDocumentsByTypePath = '/documents/types/{type}';

  /**
   * Récupérer les documents par type.
   *
   * Retourne tous les documents d'un type spécifique
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getDocumentsByType()` instead.
   *
   * This method doesn't expect any request body.
   */
  getDocumentsByType$Response(params: GetDocumentsByType$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<DocumentShortDto>>> {
    return getDocumentsByType(this.http, this.rootUrl, params, context);
  }

  /**
   * Récupérer les documents par type.
   *
   * Retourne tous les documents d'un type spécifique
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getDocumentsByType$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getDocumentsByType(params: GetDocumentsByType$Params, context?: HttpContext): Observable<Array<DocumentShortDto>> {
    return this.getDocumentsByType$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<DocumentShortDto>>): Array<DocumentShortDto> => r.body)
    );
  }

  /** Path part for operation `searchDocuments()` */
  static readonly SearchDocumentsPath = '/documents/search';

  /**
   * Rechercher des documents.
   *
   * Recherche des documents par mot-clé
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `searchDocuments()` instead.
   *
   * This method doesn't expect any request body.
   */
  searchDocuments$Response(params?: SearchDocuments$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<DocumentShortDto>>> {
    return searchDocuments(this.http, this.rootUrl, params, context);
  }

  /**
   * Rechercher des documents.
   *
   * Recherche des documents par mot-clé
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `searchDocuments$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  searchDocuments(params?: SearchDocuments$Params, context?: HttpContext): Observable<Array<DocumentShortDto>> {
    return this.searchDocuments$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<DocumentShortDto>>): Array<DocumentShortDto> => r.body)
    );
  }

  /** Path part for operation `getAllowedMimeTypes()` */
  static readonly GetAllowedMimeTypesPath = '/documents/mime-types';

  /**
   * Récupérer les types MIME autorisés.
   *
   * Retourne la liste des types MIME autorisés pour chaque type de document
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllowedMimeTypes()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllowedMimeTypes$Response(params?: GetAllowedMimeTypes$Params, context?: HttpContext): Observable<StrictHttpResponse<{
[key: string]: Array<string>;
}>> {
    return getAllowedMimeTypes(this.http, this.rootUrl, params, context);
  }

  /**
   * Récupérer les types MIME autorisés.
   *
   * Retourne la liste des types MIME autorisés pour chaque type de document
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllowedMimeTypes$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllowedMimeTypes(params?: GetAllowedMimeTypes$Params, context?: HttpContext): Observable<{
[key: string]: Array<string>;
}> {
    return this.getAllowedMimeTypes$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
[key: string]: Array<string>;
}>): {
[key: string]: Array<string>;
} => r.body)
    );
  }

  /** Path part for operation `getEmployeeDocumentContent()` */
  static readonly GetEmployeeDocumentContentPath = '/documents/employees/{employeeId}/{documentId}/content';

  /**
   * Télécharger le contenu d'un document d'employé.
   *
   * Télécharge le fichier d'un document associé à un employé
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getEmployeeDocumentContent()` instead.
   *
   * This method doesn't expect any request body.
   */
  getEmployeeDocumentContent$Response(params: GetEmployeeDocumentContent$Params, context?: HttpContext): Observable<StrictHttpResponse<Blob>> {
    return getEmployeeDocumentContent(this.http, this.rootUrl, params, context);
  }

  /**
   * Télécharger le contenu d'un document d'employé.
   *
   * Télécharge le fichier d'un document associé à un employé
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getEmployeeDocumentContent$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getEmployeeDocumentContent(params: GetEmployeeDocumentContent$Params, context?: HttpContext): Observable<Blob> {
    return this.getEmployeeDocumentContent$Response(params, context).pipe(
      map((r: StrictHttpResponse<Blob>): Blob => r.body)
    );
  }

}
