/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { createEmployee } from '../fn/employee/create-employee';
import { CreateEmployee$Params } from '../fn/employee/create-employee';
import { deleteEmployee } from '../fn/employee/delete-employee';
import { DeleteEmployee$Params } from '../fn/employee/delete-employee';
import { DepartmentEmployeeStatsDto } from '../models/department-employee-stats-dto';
import { EmployeeDto } from '../models/employee-dto';
import { getActiveEmployeeCount } from '../fn/employee/get-active-employee-count';
import { GetActiveEmployeeCount$Params } from '../fn/employee/get-active-employee-count';
import { getAllEmployees } from '../fn/employee/get-all-employees';
import { GetAllEmployees$Params } from '../fn/employee/get-all-employees';
import { getEmployeeById } from '../fn/employee/get-employee-by-id';
import { GetEmployeeById$Params } from '../fn/employee/get-employee-by-id';
import { getEmployeesByDepartment } from '../fn/employee/get-employees-by-department';
import { GetEmployeesByDepartment$Params } from '../fn/employee/get-employees-by-department';
import { getEmployeeStatsByDepartment } from '../fn/employee/get-employee-stats-by-department';
import { GetEmployeeStatsByDepartment$Params } from '../fn/employee/get-employee-stats-by-department';
import { getRecentHires } from '../fn/employee/get-recent-hires';
import { GetRecentHires$Params } from '../fn/employee/get-recent-hires';
import { getSubordinates1 } from '../fn/employee/get-subordinates-1';
import { GetSubordinates1$Params } from '../fn/employee/get-subordinates-1';
import { PageEmployeeDto } from '../models/page-employee-dto';
import { searchEmployees } from '../fn/employee/search-employees';
import { SearchEmployees$Params } from '../fn/employee/search-employees';
import { updateEmployee } from '../fn/employee/update-employee';
import { UpdateEmployee$Params } from '../fn/employee/update-employee';
import { updateEmployeeStatus } from '../fn/employee/update-employee-status';
import { UpdateEmployeeStatus$Params } from '../fn/employee/update-employee-status';


/**
 * API pour la gestion des employés
 */
@Injectable({ providedIn: 'root' })
export class EmployeeService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getEmployeeById()` */
  static readonly GetEmployeeByIdPath = '/employees/{id}';

  /**
   * Récupérer un employé par ID.
   *
   * Retourne un employé basé sur son ID
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getEmployeeById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getEmployeeById$Response(params: GetEmployeeById$Params, context?: HttpContext): Observable<StrictHttpResponse<EmployeeDto>> {
    return getEmployeeById(this.http, this.rootUrl, params, context);
  }

  /**
   * Récupérer un employé par ID.
   *
   * Retourne un employé basé sur son ID
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getEmployeeById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getEmployeeById(params: GetEmployeeById$Params, context?: HttpContext): Observable<EmployeeDto> {
    return this.getEmployeeById$Response(params, context).pipe(
      map((r: StrictHttpResponse<EmployeeDto>): EmployeeDto => r.body)
    );
  }

  /** Path part for operation `updateEmployee()` */
  static readonly UpdateEmployeePath = '/employees/{id}';

  /**
   * Mettre à jour un employé.
   *
   * Met à jour un employé existant et retourne l'employé mis à jour
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateEmployee()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateEmployee$Response(params: UpdateEmployee$Params, context?: HttpContext): Observable<StrictHttpResponse<EmployeeDto>> {
    return updateEmployee(this.http, this.rootUrl, params, context);
  }

  /**
   * Mettre à jour un employé.
   *
   * Met à jour un employé existant et retourne l'employé mis à jour
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateEmployee$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateEmployee(params: UpdateEmployee$Params, context?: HttpContext): Observable<EmployeeDto> {
    return this.updateEmployee$Response(params, context).pipe(
      map((r: StrictHttpResponse<EmployeeDto>): EmployeeDto => r.body)
    );
  }

  /** Path part for operation `deleteEmployee()` */
  static readonly DeleteEmployeePath = '/employees/{id}';

  /**
   * Supprimer un employé.
   *
   * Désactive un employé (soft delete)
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteEmployee()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteEmployee$Response(params: DeleteEmployee$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return deleteEmployee(this.http, this.rootUrl, params, context);
  }

  /**
   * Supprimer un employé.
   *
   * Désactive un employé (soft delete)
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteEmployee$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteEmployee(params: DeleteEmployee$Params, context?: HttpContext): Observable<void> {
    return this.deleteEmployee$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getAllEmployees()` */
  static readonly GetAllEmployeesPath = '/employees';

  /**
   * Récupérer tous les employés.
   *
   * Retourne une liste paginée de tous les employés
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllEmployees()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllEmployees$Response(params: GetAllEmployees$Params, context?: HttpContext): Observable<StrictHttpResponse<PageEmployeeDto>> {
    return getAllEmployees(this.http, this.rootUrl, params, context);
  }

  /**
   * Récupérer tous les employés.
   *
   * Retourne une liste paginée de tous les employés
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllEmployees$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllEmployees(params: GetAllEmployees$Params, context?: HttpContext): Observable<PageEmployeeDto> {
    return this.getAllEmployees$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageEmployeeDto>): PageEmployeeDto => r.body)
    );
  }

  /** Path part for operation `createEmployee()` */
  static readonly CreateEmployeePath = '/employees';

  /**
   * Créer un nouvel employé.
   *
   * Crée un nouvel employé et retourne l'employé créé
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createEmployee()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createEmployee$Response(params: CreateEmployee$Params, context?: HttpContext): Observable<StrictHttpResponse<EmployeeDto>> {
    return createEmployee(this.http, this.rootUrl, params, context);
  }

  /**
   * Créer un nouvel employé.
   *
   * Crée un nouvel employé et retourne l'employé créé
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createEmployee$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createEmployee(params: CreateEmployee$Params, context?: HttpContext): Observable<EmployeeDto> {
    return this.createEmployee$Response(params, context).pipe(
      map((r: StrictHttpResponse<EmployeeDto>): EmployeeDto => r.body)
    );
  }

  /** Path part for operation `updateEmployeeStatus()` */
  static readonly UpdateEmployeeStatusPath = '/employees/{id}/status';

  /**
   * Mettre à jour le statut d'un employé.
   *
   * Met à jour uniquement le statut d'un employé
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateEmployeeStatus()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateEmployeeStatus$Response(params: UpdateEmployeeStatus$Params, context?: HttpContext): Observable<StrictHttpResponse<EmployeeDto>> {
    return updateEmployeeStatus(this.http, this.rootUrl, params, context);
  }

  /**
   * Mettre à jour le statut d'un employé.
   *
   * Met à jour uniquement le statut d'un employé
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateEmployeeStatus$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateEmployeeStatus(params: UpdateEmployeeStatus$Params, context?: HttpContext): Observable<EmployeeDto> {
    return this.updateEmployeeStatus$Response(params, context).pipe(
      map((r: StrictHttpResponse<EmployeeDto>): EmployeeDto => r.body)
    );
  }

  /** Path part for operation `getSubordinates1()` */
  static readonly GetSubordinates1Path = '/employees/{id}/subordinates';

  /**
   * Récupérer les subordonnés d'un manager.
   *
   * Retourne la liste des employés qui rapportent à un manager spécifique
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getSubordinates1()` instead.
   *
   * This method doesn't expect any request body.
   */
  getSubordinates1$Response(params: GetSubordinates1$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<EmployeeDto>>> {
    return getSubordinates1(this.http, this.rootUrl, params, context);
  }

  /**
   * Récupérer les subordonnés d'un manager.
   *
   * Retourne la liste des employés qui rapportent à un manager spécifique
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getSubordinates1$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getSubordinates1(params: GetSubordinates1$Params, context?: HttpContext): Observable<Array<EmployeeDto>> {
    return this.getSubordinates1$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<EmployeeDto>>): Array<EmployeeDto> => r.body)
    );
  }

  /** Path part for operation `getEmployeeStatsByDepartment()` */
  static readonly GetEmployeeStatsByDepartmentPath = '/employees/stats';

  /**
   * Récupérer les statistiques des employés par département.
   *
   * Retourne des statistiques agrégées sur les employés par département
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getEmployeeStatsByDepartment()` instead.
   *
   * This method doesn't expect any request body.
   */
  getEmployeeStatsByDepartment$Response(params?: GetEmployeeStatsByDepartment$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<DepartmentEmployeeStatsDto>>> {
    return getEmployeeStatsByDepartment(this.http, this.rootUrl, params, context);
  }

  /**
   * Récupérer les statistiques des employés par département.
   *
   * Retourne des statistiques agrégées sur les employés par département
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getEmployeeStatsByDepartment$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getEmployeeStatsByDepartment(params?: GetEmployeeStatsByDepartment$Params, context?: HttpContext): Observable<Array<DepartmentEmployeeStatsDto>> {
    return this.getEmployeeStatsByDepartment$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<DepartmentEmployeeStatsDto>>): Array<DepartmentEmployeeStatsDto> => r.body)
    );
  }

  /** Path part for operation `searchEmployees()` */
  static readonly SearchEmployeesPath = '/employees/search';

  /**
   * Rechercher des employés.
   *
   * Recherche des employés selon différents critères
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `searchEmployees()` instead.
   *
   * This method doesn't expect any request body.
   */
  searchEmployees$Response(params: SearchEmployees$Params, context?: HttpContext): Observable<StrictHttpResponse<PageEmployeeDto>> {
    return searchEmployees(this.http, this.rootUrl, params, context);
  }

  /**
   * Rechercher des employés.
   *
   * Recherche des employés selon différents critères
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `searchEmployees$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  searchEmployees(params: SearchEmployees$Params, context?: HttpContext): Observable<PageEmployeeDto> {
    return this.searchEmployees$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageEmployeeDto>): PageEmployeeDto => r.body)
    );
  }

  /** Path part for operation `getRecentHires()` */
  static readonly GetRecentHiresPath = '/employees/recent';

  /**
   * Récupérer les employés récemment embauchés.
   *
   * Retourne la liste des employés embauchés au cours des 30 derniers jours
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getRecentHires()` instead.
   *
   * This method doesn't expect any request body.
   */
  getRecentHires$Response(params?: GetRecentHires$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<EmployeeDto>>> {
    return getRecentHires(this.http, this.rootUrl, params, context);
  }

  /**
   * Récupérer les employés récemment embauchés.
   *
   * Retourne la liste des employés embauchés au cours des 30 derniers jours
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getRecentHires$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getRecentHires(params?: GetRecentHires$Params, context?: HttpContext): Observable<Array<EmployeeDto>> {
    return this.getRecentHires$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<EmployeeDto>>): Array<EmployeeDto> => r.body)
    );
  }

  /** Path part for operation `getEmployeesByDepartment()` */
  static readonly GetEmployeesByDepartmentPath = '/employees/department/{departmentId}';

  /**
   * Récupérer les employés d'un département.
   *
   * Retourne une liste paginée des employés d'un département spécifique
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getEmployeesByDepartment()` instead.
   *
   * This method doesn't expect any request body.
   */
  getEmployeesByDepartment$Response(params: GetEmployeesByDepartment$Params, context?: HttpContext): Observable<StrictHttpResponse<PageEmployeeDto>> {
    return getEmployeesByDepartment(this.http, this.rootUrl, params, context);
  }

  /**
   * Récupérer les employés d'un département.
   *
   * Retourne une liste paginée des employés d'un département spécifique
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getEmployeesByDepartment$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getEmployeesByDepartment(params: GetEmployeesByDepartment$Params, context?: HttpContext): Observable<PageEmployeeDto> {
    return this.getEmployeesByDepartment$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageEmployeeDto>): PageEmployeeDto => r.body)
    );
  }

  /** Path part for operation `getActiveEmployeeCount()` */
  static readonly GetActiveEmployeeCountPath = '/employees/count';

  /**
   * Récupérer le nombre total d'employés actifs.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getActiveEmployeeCount()` instead.
   *
   * This method doesn't expect any request body.
   */
  getActiveEmployeeCount$Response(params?: GetActiveEmployeeCount$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
    return getActiveEmployeeCount(this.http, this.rootUrl, params, context);
  }

  /**
   * Récupérer le nombre total d'employés actifs.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getActiveEmployeeCount$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getActiveEmployeeCount(params?: GetActiveEmployeeCount$Params, context?: HttpContext): Observable<number> {
    return this.getActiveEmployeeCount$Response(params, context).pipe(
      map((r: StrictHttpResponse<number>): number => r.body)
    );
  }

}
