/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { DepartementTreeDto } from '../models/departement-tree-dto';
import { EmployeeDto } from '../models/employee-dto';
import { getDepartmentChart } from '../fn/organisation/get-department-chart';
import { GetDepartmentChart$Params } from '../fn/organisation/get-department-chart';
import { getOrganizationChart } from '../fn/organisation/get-organization-chart';
import { GetOrganizationChart$Params } from '../fn/organisation/get-organization-chart';
import { getOrganizationSummary } from '../fn/organisation/get-organization-summary';
import { GetOrganizationSummary$Params } from '../fn/organisation/get-organization-summary';
import { getSubordinates } from '../fn/organisation/get-subordinates';
import { GetSubordinates$Params } from '../fn/organisation/get-subordinates';


/**
 * API pour la gestion de l'organigramme et de la structure organisationnelle
 */
@Injectable({ providedIn: 'root' })
export class OrganisationService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getOrganizationSummary()` */
  static readonly GetOrganizationSummaryPath = '/organizations/summary';

  /**
   * Récupérer le résumé de l'organisation.
   *
   * Retourne des statistiques globales sur l'organisation
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getOrganizationSummary()` instead.
   *
   * This method doesn't expect any request body.
   */
  getOrganizationSummary$Response(params?: GetOrganizationSummary$Params, context?: HttpContext): Observable<StrictHttpResponse<{
[key: string]: {
};
}>> {
    return getOrganizationSummary(this.http, this.rootUrl, params, context);
  }

  /**
   * Récupérer le résumé de l'organisation.
   *
   * Retourne des statistiques globales sur l'organisation
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getOrganizationSummary$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getOrganizationSummary(params?: GetOrganizationSummary$Params, context?: HttpContext): Observable<{
[key: string]: {
};
}> {
    return this.getOrganizationSummary$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
[key: string]: {
};
}>): {
[key: string]: {
};
} => r.body)
    );
  }

  /** Path part for operation `getSubordinates()` */
  static readonly GetSubordinatesPath = '/organizations/employees/{employeeId}/subordinates';

  /**
   * Récupérer les subordonnés d'un manager.
   *
   * Retourne la liste des employés qui rapportent directement à un manager
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getSubordinates()` instead.
   *
   * This method doesn't expect any request body.
   */
  getSubordinates$Response(params: GetSubordinates$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<EmployeeDto>>> {
    return getSubordinates(this.http, this.rootUrl, params, context);
  }

  /**
   * Récupérer les subordonnés d'un manager.
   *
   * Retourne la liste des employés qui rapportent directement à un manager
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getSubordinates$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getSubordinates(params: GetSubordinates$Params, context?: HttpContext): Observable<Array<EmployeeDto>> {
    return this.getSubordinates$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<EmployeeDto>>): Array<EmployeeDto> => r.body)
    );
  }

  /** Path part for operation `getOrganizationChart()` */
  static readonly GetOrganizationChartPath = '/organizations/chart';

  /**
   * Récupérer l'organigramme complet.
   *
   * Retourne la structure hiérarchique de l'organisation avec départements et sous-départements
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getOrganizationChart()` instead.
   *
   * This method doesn't expect any request body.
   */
  getOrganizationChart$Response(params?: GetOrganizationChart$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<DepartementTreeDto>>> {
    return getOrganizationChart(this.http, this.rootUrl, params, context);
  }

  /**
   * Récupérer l'organigramme complet.
   *
   * Retourne la structure hiérarchique de l'organisation avec départements et sous-départements
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getOrganizationChart$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getOrganizationChart(params?: GetOrganizationChart$Params, context?: HttpContext): Observable<Array<DepartementTreeDto>> {
    return this.getOrganizationChart$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<DepartementTreeDto>>): Array<DepartementTreeDto> => r.body)
    );
  }

  /** Path part for operation `getDepartmentChart()` */
  static readonly GetDepartmentChartPath = '/organizations/chart/{departmentId}';

  /**
   * Récupérer l'organigramme d'un département.
   *
   * Retourne la structure hiérarchique à partir d'un département spécifique
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getDepartmentChart()` instead.
   *
   * This method doesn't expect any request body.
   */
  getDepartmentChart$Response(params: GetDepartmentChart$Params, context?: HttpContext): Observable<StrictHttpResponse<DepartementTreeDto>> {
    return getDepartmentChart(this.http, this.rootUrl, params, context);
  }

  /**
   * Récupérer l'organigramme d'un département.
   *
   * Retourne la structure hiérarchique à partir d'un département spécifique
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getDepartmentChart$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getDepartmentChart(params: GetDepartmentChart$Params, context?: HttpContext): Observable<DepartementTreeDto> {
    return this.getDepartmentChart$Response(params, context).pipe(
      map((r: StrictHttpResponse<DepartementTreeDto>): DepartementTreeDto => r.body)
    );
  }

}
