/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { createLeavePolicy } from '../fn/politiques-de-conges/create-leave-policy';
import { CreateLeavePolicy$Params } from '../fn/politiques-de-conges/create-leave-policy';
import { deleteLeavePolicy } from '../fn/politiques-de-conges/delete-leave-policy';
import { DeleteLeavePolicy$Params } from '../fn/politiques-de-conges/delete-leave-policy';
import { duplicateLeavePolicies } from '../fn/politiques-de-conges/duplicate-leave-policies';
import { DuplicateLeavePolicies$Params } from '../fn/politiques-de-conges/duplicate-leave-policies';
import { getAllLeavePolicies } from '../fn/politiques-de-conges/get-all-leave-policies';
import { GetAllLeavePolicies$Params } from '../fn/politiques-de-conges/get-all-leave-policies';
import { getLeavePoliciesByYear } from '../fn/politiques-de-conges/get-leave-policies-by-year';
import { GetLeavePoliciesByYear$Params } from '../fn/politiques-de-conges/get-leave-policies-by-year';
import { getLeavePolicyById } from '../fn/politiques-de-conges/get-leave-policy-by-id';
import { GetLeavePolicyById$Params } from '../fn/politiques-de-conges/get-leave-policy-by-id';
import { getLeavePolicyByTypeAndYear } from '../fn/politiques-de-conges/get-leave-policy-by-type-and-year';
import { GetLeavePolicyByTypeAndYear$Params } from '../fn/politiques-de-conges/get-leave-policy-by-type-and-year';
import { LeavePolicyDto } from '../models/leave-policy-dto';
import { updateLeavePolicy } from '../fn/politiques-de-conges/update-leave-policy';
import { UpdateLeavePolicy$Params } from '../fn/politiques-de-conges/update-leave-policy';


/**
 * API pour la gestion des politiques de congés
 */
@Injectable({ providedIn: 'root' })
export class PolitiquesDeCongesService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getLeavePolicyById()` */
  static readonly GetLeavePolicyByIdPath = '/leave-policies/{id}';

  /**
   * Récupérer une politique de congés par ID.
   *
   * Retourne une politique de congés spécifique par son ID
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getLeavePolicyById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getLeavePolicyById$Response(params: GetLeavePolicyById$Params, context?: HttpContext): Observable<StrictHttpResponse<LeavePolicyDto>> {
    return getLeavePolicyById(this.http, this.rootUrl, params, context);
  }

  /**
   * Récupérer une politique de congés par ID.
   *
   * Retourne une politique de congés spécifique par son ID
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getLeavePolicyById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getLeavePolicyById(params: GetLeavePolicyById$Params, context?: HttpContext): Observable<LeavePolicyDto> {
    return this.getLeavePolicyById$Response(params, context).pipe(
      map((r: StrictHttpResponse<LeavePolicyDto>): LeavePolicyDto => r.body)
    );
  }

  /** Path part for operation `updateLeavePolicy()` */
  static readonly UpdateLeavePolicyPath = '/leave-policies/{id}';

  /**
   * Mettre à jour une politique de congés.
   *
   * Met à jour une politique de congés existante
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateLeavePolicy()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateLeavePolicy$Response(params: UpdateLeavePolicy$Params, context?: HttpContext): Observable<StrictHttpResponse<LeavePolicyDto>> {
    return updateLeavePolicy(this.http, this.rootUrl, params, context);
  }

  /**
   * Mettre à jour une politique de congés.
   *
   * Met à jour une politique de congés existante
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateLeavePolicy$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateLeavePolicy(params: UpdateLeavePolicy$Params, context?: HttpContext): Observable<LeavePolicyDto> {
    return this.updateLeavePolicy$Response(params, context).pipe(
      map((r: StrictHttpResponse<LeavePolicyDto>): LeavePolicyDto => r.body)
    );
  }

  /** Path part for operation `deleteLeavePolicy()` */
  static readonly DeleteLeavePolicyPath = '/leave-policies/{id}';

  /**
   * Supprimer une politique de congés.
   *
   * Supprime une politique de congés existante
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteLeavePolicy()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteLeavePolicy$Response(params: DeleteLeavePolicy$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return deleteLeavePolicy(this.http, this.rootUrl, params, context);
  }

  /**
   * Supprimer une politique de congés.
   *
   * Supprime une politique de congés existante
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteLeavePolicy$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteLeavePolicy(params: DeleteLeavePolicy$Params, context?: HttpContext): Observable<void> {
    return this.deleteLeavePolicy$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getAllLeavePolicies()` */
  static readonly GetAllLeavePoliciesPath = '/leave-policies';

  /**
   * Récupérer toutes les politiques de congés.
   *
   * Retourne une liste de toutes les politiques de congés
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllLeavePolicies()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllLeavePolicies$Response(params?: GetAllLeavePolicies$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<LeavePolicyDto>>> {
    return getAllLeavePolicies(this.http, this.rootUrl, params, context);
  }

  /**
   * Récupérer toutes les politiques de congés.
   *
   * Retourne une liste de toutes les politiques de congés
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllLeavePolicies$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllLeavePolicies(params?: GetAllLeavePolicies$Params, context?: HttpContext): Observable<Array<LeavePolicyDto>> {
    return this.getAllLeavePolicies$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<LeavePolicyDto>>): Array<LeavePolicyDto> => r.body)
    );
  }

  /** Path part for operation `createLeavePolicy()` */
  static readonly CreateLeavePolicyPath = '/leave-policies';

  /**
   * Créer une nouvelle politique de congés.
   *
   * Crée une nouvelle politique de congés et retourne la politique créée
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createLeavePolicy()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createLeavePolicy$Response(params: CreateLeavePolicy$Params, context?: HttpContext): Observable<StrictHttpResponse<LeavePolicyDto>> {
    return createLeavePolicy(this.http, this.rootUrl, params, context);
  }

  /**
   * Créer une nouvelle politique de congés.
   *
   * Crée une nouvelle politique de congés et retourne la politique créée
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createLeavePolicy$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createLeavePolicy(params: CreateLeavePolicy$Params, context?: HttpContext): Observable<LeavePolicyDto> {
    return this.createLeavePolicy$Response(params, context).pipe(
      map((r: StrictHttpResponse<LeavePolicyDto>): LeavePolicyDto => r.body)
    );
  }

  /** Path part for operation `duplicateLeavePolicies()` */
  static readonly DuplicateLeavePoliciesPath = '/leave-policies/duplicate';

  /**
   * Dupliquer des politiques de congés.
   *
   * Duplique des politiques de congés d'une année à une autre
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `duplicateLeavePolicies()` instead.
   *
   * This method doesn't expect any request body.
   */
  duplicateLeavePolicies$Response(params: DuplicateLeavePolicies$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<LeavePolicyDto>>> {
    return duplicateLeavePolicies(this.http, this.rootUrl, params, context);
  }

  /**
   * Dupliquer des politiques de congés.
   *
   * Duplique des politiques de congés d'une année à une autre
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `duplicateLeavePolicies$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  duplicateLeavePolicies(params: DuplicateLeavePolicies$Params, context?: HttpContext): Observable<Array<LeavePolicyDto>> {
    return this.duplicateLeavePolicies$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<LeavePolicyDto>>): Array<LeavePolicyDto> => r.body)
    );
  }

  /** Path part for operation `getLeavePoliciesByYear()` */
  static readonly GetLeavePoliciesByYearPath = '/leave-policies/year/{year}';

  /**
   * Récupérer les politiques de congés pour une année donnée.
   *
   * Retourne les politiques de congés pour une année spécifique
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getLeavePoliciesByYear()` instead.
   *
   * This method doesn't expect any request body.
   */
  getLeavePoliciesByYear$Response(params: GetLeavePoliciesByYear$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<LeavePolicyDto>>> {
    return getLeavePoliciesByYear(this.http, this.rootUrl, params, context);
  }

  /**
   * Récupérer les politiques de congés pour une année donnée.
   *
   * Retourne les politiques de congés pour une année spécifique
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getLeavePoliciesByYear$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getLeavePoliciesByYear(params: GetLeavePoliciesByYear$Params, context?: HttpContext): Observable<Array<LeavePolicyDto>> {
    return this.getLeavePoliciesByYear$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<LeavePolicyDto>>): Array<LeavePolicyDto> => r.body)
    );
  }

  /** Path part for operation `getLeavePolicyByTypeAndYear()` */
  static readonly GetLeavePolicyByTypeAndYearPath = '/leave-policies/type/{leaveType}/year/{year}';

  /**
   * Récupérer une politique de congés par type et année.
   *
   * Retourne une politique de congés pour un type et une année spécifiques
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getLeavePolicyByTypeAndYear()` instead.
   *
   * This method doesn't expect any request body.
   */
  getLeavePolicyByTypeAndYear$Response(params: GetLeavePolicyByTypeAndYear$Params, context?: HttpContext): Observable<StrictHttpResponse<LeavePolicyDto>> {
    return getLeavePolicyByTypeAndYear(this.http, this.rootUrl, params, context);
  }

  /**
   * Récupérer une politique de congés par type et année.
   *
   * Retourne une politique de congés pour un type et une année spécifiques
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getLeavePolicyByTypeAndYear$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getLeavePolicyByTypeAndYear(params: GetLeavePolicyByTypeAndYear$Params, context?: HttpContext): Observable<LeavePolicyDto> {
    return this.getLeavePolicyByTypeAndYear$Response(params, context).pipe(
      map((r: StrictHttpResponse<LeavePolicyDto>): LeavePolicyDto => r.body)
    );
  }

}
