/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { checkTitleExists } from '../fn/positions/check-title-exists';
import { CheckTitleExists$Params } from '../fn/positions/check-title-exists';
import { createPosition } from '../fn/positions/create-position';
import { CreatePosition$Params } from '../fn/positions/create-position';
import { deletePosition } from '../fn/positions/delete-position';
import { DeletePosition$Params } from '../fn/positions/delete-position';
import { getActivePositions } from '../fn/positions/get-active-positions';
import { GetActivePositions$Params } from '../fn/positions/get-active-positions';
import { getAllPositions } from '../fn/positions/get-all-positions';
import { GetAllPositions$Params } from '../fn/positions/get-all-positions';
import { getPositionById } from '../fn/positions/get-position-by-id';
import { GetPositionById$Params } from '../fn/positions/get-position-by-id';
import { getPositionsByDepartment } from '../fn/positions/get-positions-by-department';
import { GetPositionsByDepartment$Params } from '../fn/positions/get-positions-by-department';
import { getPositionsBySalaryRange } from '../fn/positions/get-positions-by-salary-range';
import { GetPositionsBySalaryRange$Params } from '../fn/positions/get-positions-by-salary-range';
import { Page } from '../models/page';
import { PositionDto } from '../models/position-dto';
import { searchPositions } from '../fn/positions/search-positions';
import { SearchPositions$Params } from '../fn/positions/search-positions';
import { updatePosition } from '../fn/positions/update-position';
import { UpdatePosition$Params } from '../fn/positions/update-position';
import { updatePositionStatus } from '../fn/positions/update-position-status';
import { UpdatePositionStatus$Params } from '../fn/positions/update-position-status';


/**
 * API pour gérer les postes dans le système RH
 */
@Injectable({ providedIn: 'root' })
export class PositionsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getPositionById()` */
  static readonly GetPositionByIdPath = '/api/positions/{id}';

  /**
   * Récupérer une position par ID.
   *
   * Récupère les détails d'une position spécifique par son ID
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getPositionById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPositionById$Response(params: GetPositionById$Params, context?: HttpContext): Observable<StrictHttpResponse<PositionDto>> {
    return getPositionById(this.http, this.rootUrl, params, context);
  }

  /**
   * Récupérer une position par ID.
   *
   * Récupère les détails d'une position spécifique par son ID
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getPositionById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPositionById(params: GetPositionById$Params, context?: HttpContext): Observable<PositionDto> {
    return this.getPositionById$Response(params, context).pipe(
      map((r: StrictHttpResponse<PositionDto>): PositionDto => r.body)
    );
  }

  /** Path part for operation `updatePosition()` */
  static readonly UpdatePositionPath = '/api/positions/{id}';

  /**
   * Mettre à jour une position.
   *
   * Met à jour les détails d'une position existante
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updatePosition()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updatePosition$Response(params: UpdatePosition$Params, context?: HttpContext): Observable<StrictHttpResponse<PositionDto>> {
    return updatePosition(this.http, this.rootUrl, params, context);
  }

  /**
   * Mettre à jour une position.
   *
   * Met à jour les détails d'une position existante
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updatePosition$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updatePosition(params: UpdatePosition$Params, context?: HttpContext): Observable<PositionDto> {
    return this.updatePosition$Response(params, context).pipe(
      map((r: StrictHttpResponse<PositionDto>): PositionDto => r.body)
    );
  }

  /** Path part for operation `deletePosition()` */
  static readonly DeletePositionPath = '/api/positions/{id}';

  /**
   * Supprimer une position.
   *
   * Supprime une position si elle n'est pas utilisée
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deletePosition()` instead.
   *
   * This method doesn't expect any request body.
   */
  deletePosition$Response(params: DeletePosition$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return deletePosition(this.http, this.rootUrl, params, context);
  }

  /**
   * Supprimer une position.
   *
   * Supprime une position si elle n'est pas utilisée
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deletePosition$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deletePosition(params: DeletePosition$Params, context?: HttpContext): Observable<void> {
    return this.deletePosition$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getAllPositions()` */
  static readonly GetAllPositionsPath = '/api/positions';

  /**
   * Récupérer toutes les positions.
   *
   * Récupère la liste paginée de toutes les positions
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllPositions()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllPositions$Response(params: GetAllPositions$Params, context?: HttpContext): Observable<StrictHttpResponse<Page>> {
    return getAllPositions(this.http, this.rootUrl, params, context);
  }

  /**
   * Récupérer toutes les positions.
   *
   * Récupère la liste paginée de toutes les positions
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllPositions$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllPositions(params: GetAllPositions$Params, context?: HttpContext): Observable<Page> {
    return this.getAllPositions$Response(params, context).pipe(
      map((r: StrictHttpResponse<Page>): Page => r.body)
    );
  }

  /** Path part for operation `createPosition()` */
  static readonly CreatePositionPath = '/api/positions';

  /**
   * Créer une nouvelle position.
   *
   * Crée une nouvelle position dans le système
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createPosition()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createPosition$Response(params: CreatePosition$Params, context?: HttpContext): Observable<StrictHttpResponse<PositionDto>> {
    return createPosition(this.http, this.rootUrl, params, context);
  }

  /**
   * Créer une nouvelle position.
   *
   * Crée une nouvelle position dans le système
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createPosition$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createPosition(params: CreatePosition$Params, context?: HttpContext): Observable<PositionDto> {
    return this.createPosition$Response(params, context).pipe(
      map((r: StrictHttpResponse<PositionDto>): PositionDto => r.body)
    );
  }

  /** Path part for operation `updatePositionStatus()` */
  static readonly UpdatePositionStatusPath = '/api/positions/{id}/status';

  /**
   * Mettre à jour le statut d'une position.
   *
   * Active ou désactive une position
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updatePositionStatus()` instead.
   *
   * This method doesn't expect any request body.
   */
  updatePositionStatus$Response(params: UpdatePositionStatus$Params, context?: HttpContext): Observable<StrictHttpResponse<PositionDto>> {
    return updatePositionStatus(this.http, this.rootUrl, params, context);
  }

  /**
   * Mettre à jour le statut d'une position.
   *
   * Active ou désactive une position
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updatePositionStatus$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  updatePositionStatus(params: UpdatePositionStatus$Params, context?: HttpContext): Observable<PositionDto> {
    return this.updatePositionStatus$Response(params, context).pipe(
      map((r: StrictHttpResponse<PositionDto>): PositionDto => r.body)
    );
  }

  /** Path part for operation `searchPositions()` */
  static readonly SearchPositionsPath = '/api/positions/search';

  /**
   * Rechercher des positions.
   *
   * Recherche des positions selon différents critères
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `searchPositions()` instead.
   *
   * This method doesn't expect any request body.
   */
  searchPositions$Response(params: SearchPositions$Params, context?: HttpContext): Observable<StrictHttpResponse<Page>> {
    return searchPositions(this.http, this.rootUrl, params, context);
  }

  /**
   * Rechercher des positions.
   *
   * Recherche des positions selon différents critères
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `searchPositions$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  searchPositions(params: SearchPositions$Params, context?: HttpContext): Observable<Page> {
    return this.searchPositions$Response(params, context).pipe(
      map((r: StrictHttpResponse<Page>): Page => r.body)
    );
  }

  /** Path part for operation `getPositionsBySalaryRange()` */
  static readonly GetPositionsBySalaryRangePath = '/api/positions/salary-range';

  /**
   * Récupérer les positions par plage de salaire.
   *
   * Récupère toutes les positions dont la plage salariale est comprise entre les valeurs spécifiées
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getPositionsBySalaryRange()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPositionsBySalaryRange$Response(params: GetPositionsBySalaryRange$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
    return getPositionsBySalaryRange(this.http, this.rootUrl, params, context);
  }

  /**
   * Récupérer les positions par plage de salaire.
   *
   * Récupère toutes les positions dont la plage salariale est comprise entre les valeurs spécifiées
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getPositionsBySalaryRange$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPositionsBySalaryRange(params: GetPositionsBySalaryRange$Params, context?: HttpContext): Observable<string> {
    return this.getPositionsBySalaryRange$Response(params, context).pipe(
      map((r: StrictHttpResponse<string>): string => r.body)
    );
  }

  /** Path part for operation `getPositionsByDepartment()` */
  static readonly GetPositionsByDepartmentPath = '/api/positions/department/{departmentId}';

  /**
   * Récupérer les positions par département.
   *
   * Récupère toutes les positions associées à un département spécifique
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getPositionsByDepartment()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPositionsByDepartment$Response(params: GetPositionsByDepartment$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
    return getPositionsByDepartment(this.http, this.rootUrl, params, context);
  }

  /**
   * Récupérer les positions par département.
   *
   * Récupère toutes les positions associées à un département spécifique
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getPositionsByDepartment$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPositionsByDepartment(params: GetPositionsByDepartment$Params, context?: HttpContext): Observable<string> {
    return this.getPositionsByDepartment$Response(params, context).pipe(
      map((r: StrictHttpResponse<string>): string => r.body)
    );
  }

  /** Path part for operation `checkTitleExists()` */
  static readonly CheckTitleExistsPath = '/api/positions/check-title';

  /**
   * Vérifier l'unicité d'un titre.
   *
   * Vérifie si un titre de position existe déjà (utile pour la validation côté client)
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `checkTitleExists()` instead.
   *
   * This method doesn't expect any request body.
   */
  checkTitleExists$Response(params: CheckTitleExists$Params, context?: HttpContext): Observable<StrictHttpResponse<boolean>> {
    return checkTitleExists(this.http, this.rootUrl, params, context);
  }

  /**
   * Vérifier l'unicité d'un titre.
   *
   * Vérifie si un titre de position existe déjà (utile pour la validation côté client)
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `checkTitleExists$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  checkTitleExists(params: CheckTitleExists$Params, context?: HttpContext): Observable<boolean> {
    return this.checkTitleExists$Response(params, context).pipe(
      map((r: StrictHttpResponse<boolean>): boolean => r.body)
    );
  }

  /** Path part for operation `getActivePositions()` */
  static readonly GetActivePositionsPath = '/api/positions/active';

  /**
   * Récupérer les positions actives.
   *
   * Récupère toutes les positions marquées comme actives
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getActivePositions()` instead.
   *
   * This method doesn't expect any request body.
   */
  getActivePositions$Response(params?: GetActivePositions$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
    return getActivePositions(this.http, this.rootUrl, params, context);
  }

  /**
   * Récupérer les positions actives.
   *
   * Récupère toutes les positions marquées comme actives
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getActivePositions$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getActivePositions(params?: GetActivePositions$Params, context?: HttpContext): Observable<string> {
    return this.getActivePositions$Response(params, context).pipe(
      map((r: StrictHttpResponse<string>): string => r.body)
    );
  }

}
