/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { AbsenteeismReportDto } from '../models/absenteeism-report-dto';
import { EmployeeDistributionReportDto } from '../models/employee-distribution-report-dto';
import { generateReport } from '../fn/rapports/generate-report';
import { GenerateReport$Params } from '../fn/rapports/generate-report';
import { getAbsenteeismReport } from '../fn/rapports/get-absenteeism-report';
import { GetAbsenteeismReport$Params } from '../fn/rapports/get-absenteeism-report';
import { getAbsenteeismReportForPeriod } from '../fn/rapports/get-absenteeism-report-for-period';
import { GetAbsenteeismReportForPeriod$Params } from '../fn/rapports/get-absenteeism-report-for-period';
import { getCurrentEmployeeDistributionReport } from '../fn/rapports/get-current-employee-distribution-report';
import { GetCurrentEmployeeDistributionReport$Params } from '../fn/rapports/get-current-employee-distribution-report';
import { getDashboardSummary } from '../fn/rapports/get-dashboard-summary';
import { GetDashboardSummary$Params } from '../fn/rapports/get-dashboard-summary';
import { getEmployeeDistributionReport } from '../fn/rapports/get-employee-distribution-report';
import { GetEmployeeDistributionReport$Params } from '../fn/rapports/get-employee-distribution-report';
import { getSalaryCostReport } from '../fn/rapports/get-salary-cost-report';
import { GetSalaryCostReport$Params } from '../fn/rapports/get-salary-cost-report';
import { getTurnoverReport } from '../fn/rapports/get-turnover-report';
import { GetTurnoverReport$Params } from '../fn/rapports/get-turnover-report';
import { SalaryCostReportDto } from '../models/salary-cost-report-dto';
import { TurnoverReportDto } from '../models/turnover-report-dto';


/**
 * API pour la génération de rapports et statistiques RH
 */
@Injectable({ providedIn: 'root' })
export class RapportsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getTurnoverReport()` */
  static readonly GetTurnoverReportPath = '/reports/turnover/{year}';

  /**
   * Rapport de turnover.
   *
   * Génère un rapport de turnover pour une année spécifique
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getTurnoverReport()` instead.
   *
   * This method doesn't expect any request body.
   */
  getTurnoverReport$Response(params: GetTurnoverReport$Params, context?: HttpContext): Observable<StrictHttpResponse<TurnoverReportDto>> {
    return getTurnoverReport(this.http, this.rootUrl, params, context);
  }

  /**
   * Rapport de turnover.
   *
   * Génère un rapport de turnover pour une année spécifique
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getTurnoverReport$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getTurnoverReport(params: GetTurnoverReport$Params, context?: HttpContext): Observable<TurnoverReportDto> {
    return this.getTurnoverReport$Response(params, context).pipe(
      map((r: StrictHttpResponse<TurnoverReportDto>): TurnoverReportDto => r.body)
    );
  }

  /** Path part for operation `getSalaryCostReport()` */
  static readonly GetSalaryCostReportPath = '/reports/salary/{year}';

  /**
   * Rapport des coûts salariaux.
   *
   * Génère un rapport des coûts salariaux pour une année spécifique
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getSalaryCostReport()` instead.
   *
   * This method doesn't expect any request body.
   */
  getSalaryCostReport$Response(params: GetSalaryCostReport$Params, context?: HttpContext): Observable<StrictHttpResponse<SalaryCostReportDto>> {
    return getSalaryCostReport(this.http, this.rootUrl, params, context);
  }

  /**
   * Rapport des coûts salariaux.
   *
   * Génère un rapport des coûts salariaux pour une année spécifique
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getSalaryCostReport$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getSalaryCostReport(params: GetSalaryCostReport$Params, context?: HttpContext): Observable<SalaryCostReportDto> {
    return this.getSalaryCostReport$Response(params, context).pipe(
      map((r: StrictHttpResponse<SalaryCostReportDto>): SalaryCostReportDto => r.body)
    );
  }

  /** Path part for operation `generateReport()` */
  static readonly GenerateReportPath = '/reports/generate';

  /**
   * Générer un rapport.
   *
   * Génère un rapport selon le type et les paramètres spécifiés
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `generateReport()` instead.
   *
   * This method doesn't expect any request body.
   */
  generateReport$Response(params: GenerateReport$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
    return generateReport(this.http, this.rootUrl, params, context);
  }

  /**
   * Générer un rapport.
   *
   * Génère un rapport selon le type et les paramètres spécifiés
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `generateReport$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  generateReport(params: GenerateReport$Params, context?: HttpContext): Observable<string> {
    return this.generateReport$Response(params, context).pipe(
      map((r: StrictHttpResponse<string>): string => r.body)
    );
  }

  /** Path part for operation `getCurrentEmployeeDistributionReport()` */
  static readonly GetCurrentEmployeeDistributionReportPath = '/reports/distribution';

  /**
   * Rapport de distribution des employés actuel.
   *
   * Génère un rapport sur la distribution actuelle des employés
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getCurrentEmployeeDistributionReport()` instead.
   *
   * This method doesn't expect any request body.
   */
  getCurrentEmployeeDistributionReport$Response(params?: GetCurrentEmployeeDistributionReport$Params, context?: HttpContext): Observable<StrictHttpResponse<EmployeeDistributionReportDto>> {
    return getCurrentEmployeeDistributionReport(this.http, this.rootUrl, params, context);
  }

  /**
   * Rapport de distribution des employés actuel.
   *
   * Génère un rapport sur la distribution actuelle des employés
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getCurrentEmployeeDistributionReport$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getCurrentEmployeeDistributionReport(params?: GetCurrentEmployeeDistributionReport$Params, context?: HttpContext): Observable<EmployeeDistributionReportDto> {
    return this.getCurrentEmployeeDistributionReport$Response(params, context).pipe(
      map((r: StrictHttpResponse<EmployeeDistributionReportDto>): EmployeeDistributionReportDto => r.body)
    );
  }

  /** Path part for operation `getEmployeeDistributionReport()` */
  static readonly GetEmployeeDistributionReportPath = '/reports/distribution/date';

  /**
   * Rapport de distribution des employés à une date.
   *
   * Génère un rapport sur la distribution des employés à une date spécifique
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getEmployeeDistributionReport()` instead.
   *
   * This method doesn't expect any request body.
   */
  getEmployeeDistributionReport$Response(params: GetEmployeeDistributionReport$Params, context?: HttpContext): Observable<StrictHttpResponse<EmployeeDistributionReportDto>> {
    return getEmployeeDistributionReport(this.http, this.rootUrl, params, context);
  }

  /**
   * Rapport de distribution des employés à une date.
   *
   * Génère un rapport sur la distribution des employés à une date spécifique
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getEmployeeDistributionReport$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getEmployeeDistributionReport(params: GetEmployeeDistributionReport$Params, context?: HttpContext): Observable<EmployeeDistributionReportDto> {
    return this.getEmployeeDistributionReport$Response(params, context).pipe(
      map((r: StrictHttpResponse<EmployeeDistributionReportDto>): EmployeeDistributionReportDto => r.body)
    );
  }

  /** Path part for operation `getDashboardSummary()` */
  static readonly GetDashboardSummaryPath = '/reports/dashboard/summary';

  /**
   * Résumé pour le tableau de bord.
   *
   * Fournit un résumé des indicateurs clés pour le tableau de bord
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getDashboardSummary()` instead.
   *
   * This method doesn't expect any request body.
   */
  getDashboardSummary$Response(params?: GetDashboardSummary$Params, context?: HttpContext): Observable<StrictHttpResponse<{
[key: string]: {
};
}>> {
    return getDashboardSummary(this.http, this.rootUrl, params, context);
  }

  /**
   * Résumé pour le tableau de bord.
   *
   * Fournit un résumé des indicateurs clés pour le tableau de bord
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getDashboardSummary$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getDashboardSummary(params?: GetDashboardSummary$Params, context?: HttpContext): Observable<{
[key: string]: {
};
}> {
    return this.getDashboardSummary$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
[key: string]: {
};
}>): {
[key: string]: {
};
} => r.body)
    );
  }

  /** Path part for operation `getAbsenteeismReport()` */
  static readonly GetAbsenteeismReportPath = '/reports/absenteeism/{year}';

  /**
   * Rapport d'absentéisme annuel.
   *
   * Génère un rapport d'absentéisme pour une année spécifique
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAbsenteeismReport()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAbsenteeismReport$Response(params: GetAbsenteeismReport$Params, context?: HttpContext): Observable<StrictHttpResponse<AbsenteeismReportDto>> {
    return getAbsenteeismReport(this.http, this.rootUrl, params, context);
  }

  /**
   * Rapport d'absentéisme annuel.
   *
   * Génère un rapport d'absentéisme pour une année spécifique
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAbsenteeismReport$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAbsenteeismReport(params: GetAbsenteeismReport$Params, context?: HttpContext): Observable<AbsenteeismReportDto> {
    return this.getAbsenteeismReport$Response(params, context).pipe(
      map((r: StrictHttpResponse<AbsenteeismReportDto>): AbsenteeismReportDto => r.body)
    );
  }

  /** Path part for operation `getAbsenteeismReportForPeriod()` */
  static readonly GetAbsenteeismReportForPeriodPath = '/reports/absenteeism/period';

  /**
   * Rapport d'absentéisme pour une période.
   *
   * Génère un rapport d'absentéisme pour une période spécifique
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAbsenteeismReportForPeriod()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAbsenteeismReportForPeriod$Response(params: GetAbsenteeismReportForPeriod$Params, context?: HttpContext): Observable<StrictHttpResponse<AbsenteeismReportDto>> {
    return getAbsenteeismReportForPeriod(this.http, this.rootUrl, params, context);
  }

  /**
   * Rapport d'absentéisme pour une période.
   *
   * Génère un rapport d'absentéisme pour une période spécifique
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAbsenteeismReportForPeriod$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAbsenteeismReportForPeriod(params: GetAbsenteeismReportForPeriod$Params, context?: HttpContext): Observable<AbsenteeismReportDto> {
    return this.getAbsenteeismReportForPeriod$Response(params, context).pipe(
      map((r: StrictHttpResponse<AbsenteeismReportDto>): AbsenteeismReportDto => r.body)
    );
  }

}
