/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { adjustLeaveBalance } from '../fn/soldes-de-conges/adjust-leave-balance';
import { AdjustLeaveBalance$Params } from '../fn/soldes-de-conges/adjust-leave-balance';
import { createLeaveBalance } from '../fn/soldes-de-conges/create-leave-balance';
import { CreateLeaveBalance$Params } from '../fn/soldes-de-conges/create-leave-balance';
import { getAllLeaveBalances } from '../fn/soldes-de-conges/get-all-leave-balances';
import { GetAllLeaveBalances$Params } from '../fn/soldes-de-conges/get-all-leave-balances';
import { getEmployeeLeaveBalances } from '../fn/soldes-de-conges/get-employee-leave-balances';
import { GetEmployeeLeaveBalances$Params } from '../fn/soldes-de-conges/get-employee-leave-balances';
import { getEmployeeLeaveBalancesByYear } from '../fn/soldes-de-conges/get-employee-leave-balances-by-year';
import { GetEmployeeLeaveBalancesByYear$Params } from '../fn/soldes-de-conges/get-employee-leave-balances-by-year';
import { getLeaveBalanceById } from '../fn/soldes-de-conges/get-leave-balance-by-id';
import { GetLeaveBalanceById$Params } from '../fn/soldes-de-conges/get-leave-balance-by-id';
import { initializeYearlyLeaveBalances } from '../fn/soldes-de-conges/initialize-yearly-leave-balances';
import { InitializeYearlyLeaveBalances$Params } from '../fn/soldes-de-conges/initialize-yearly-leave-balances';
import { LeaveBalanceDto } from '../models/leave-balance-dto';


/**
 * API pour la gestion des soldes de congés
 */
@Injectable({ providedIn: 'root' })
export class SoldesDeCongesService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getAllLeaveBalances()` */
  static readonly GetAllLeaveBalancesPath = '/leave-balances';

  /**
   * Récupérer tous les soldes de congés.
   *
   * Retourne une liste de tous les soldes de congés
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllLeaveBalances()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllLeaveBalances$Response(params?: GetAllLeaveBalances$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<LeaveBalanceDto>>> {
    return getAllLeaveBalances(this.http, this.rootUrl, params, context);
  }

  /**
   * Récupérer tous les soldes de congés.
   *
   * Retourne une liste de tous les soldes de congés
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllLeaveBalances$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllLeaveBalances(params?: GetAllLeaveBalances$Params, context?: HttpContext): Observable<Array<LeaveBalanceDto>> {
    return this.getAllLeaveBalances$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<LeaveBalanceDto>>): Array<LeaveBalanceDto> => r.body)
    );
  }

  /** Path part for operation `createLeaveBalance()` */
  static readonly CreateLeaveBalancePath = '/leave-balances';

  /**
   * Créer un nouveau solde de congés.
   *
   * Crée un nouveau solde de congés et retourne le solde créé
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createLeaveBalance()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createLeaveBalance$Response(params: CreateLeaveBalance$Params, context?: HttpContext): Observable<StrictHttpResponse<LeaveBalanceDto>> {
    return createLeaveBalance(this.http, this.rootUrl, params, context);
  }

  /**
   * Créer un nouveau solde de congés.
   *
   * Crée un nouveau solde de congés et retourne le solde créé
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createLeaveBalance$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createLeaveBalance(params: CreateLeaveBalance$Params, context?: HttpContext): Observable<LeaveBalanceDto> {
    return this.createLeaveBalance$Response(params, context).pipe(
      map((r: StrictHttpResponse<LeaveBalanceDto>): LeaveBalanceDto => r.body)
    );
  }

  /** Path part for operation `initializeYearlyLeaveBalances()` */
  static readonly InitializeYearlyLeaveBalancesPath = '/leave-balances/init-year/{year}';

  /**
   * Initialiser les soldes de congés pour une année.
   *
   * Initialise les soldes de congés pour tous les employés pour une année donnée
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `initializeYearlyLeaveBalances()` instead.
   *
   * This method doesn't expect any request body.
   */
  initializeYearlyLeaveBalances$Response(params: InitializeYearlyLeaveBalances$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return initializeYearlyLeaveBalances(this.http, this.rootUrl, params, context);
  }

  /**
   * Initialiser les soldes de congés pour une année.
   *
   * Initialise les soldes de congés pour tous les employés pour une année donnée
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `initializeYearlyLeaveBalances$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  initializeYearlyLeaveBalances(params: InitializeYearlyLeaveBalances$Params, context?: HttpContext): Observable<void> {
    return this.initializeYearlyLeaveBalances$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `adjustLeaveBalance()` */
  static readonly AdjustLeaveBalancePath = '/leave-balances/{id}/adjust';

  /**
   * Ajuster un solde de congés.
   *
   * Ajuste un solde de congés existant
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `adjustLeaveBalance()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  adjustLeaveBalance$Response(params: AdjustLeaveBalance$Params, context?: HttpContext): Observable<StrictHttpResponse<LeaveBalanceDto>> {
    return adjustLeaveBalance(this.http, this.rootUrl, params, context);
  }

  /**
   * Ajuster un solde de congés.
   *
   * Ajuste un solde de congés existant
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `adjustLeaveBalance$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  adjustLeaveBalance(params: AdjustLeaveBalance$Params, context?: HttpContext): Observable<LeaveBalanceDto> {
    return this.adjustLeaveBalance$Response(params, context).pipe(
      map((r: StrictHttpResponse<LeaveBalanceDto>): LeaveBalanceDto => r.body)
    );
  }

  /** Path part for operation `getLeaveBalanceById()` */
  static readonly GetLeaveBalanceByIdPath = '/leave-balances/{id}';

  /**
   * Récupérer un solde de congés par ID.
   *
   * Retourne un solde de congés spécifique par son ID
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getLeaveBalanceById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getLeaveBalanceById$Response(params: GetLeaveBalanceById$Params, context?: HttpContext): Observable<StrictHttpResponse<LeaveBalanceDto>> {
    return getLeaveBalanceById(this.http, this.rootUrl, params, context);
  }

  /**
   * Récupérer un solde de congés par ID.
   *
   * Retourne un solde de congés spécifique par son ID
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getLeaveBalanceById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getLeaveBalanceById(params: GetLeaveBalanceById$Params, context?: HttpContext): Observable<LeaveBalanceDto> {
    return this.getLeaveBalanceById$Response(params, context).pipe(
      map((r: StrictHttpResponse<LeaveBalanceDto>): LeaveBalanceDto => r.body)
    );
  }

  /** Path part for operation `getEmployeeLeaveBalances()` */
  static readonly GetEmployeeLeaveBalancesPath = '/leave-balances/employee/{employeeId}';

  /**
   * Récupérer les soldes de congés d'un employé.
   *
   * Retourne les soldes de congés d'un employé spécifique
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getEmployeeLeaveBalances()` instead.
   *
   * This method doesn't expect any request body.
   */
  getEmployeeLeaveBalances$Response(params: GetEmployeeLeaveBalances$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<LeaveBalanceDto>>> {
    return getEmployeeLeaveBalances(this.http, this.rootUrl, params, context);
  }

  /**
   * Récupérer les soldes de congés d'un employé.
   *
   * Retourne les soldes de congés d'un employé spécifique
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getEmployeeLeaveBalances$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getEmployeeLeaveBalances(params: GetEmployeeLeaveBalances$Params, context?: HttpContext): Observable<Array<LeaveBalanceDto>> {
    return this.getEmployeeLeaveBalances$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<LeaveBalanceDto>>): Array<LeaveBalanceDto> => r.body)
    );
  }

  /** Path part for operation `getEmployeeLeaveBalancesByYear()` */
  static readonly GetEmployeeLeaveBalancesByYearPath = '/leave-balances/employee/{employeeId}/year/{year}';

  /**
   * Récupérer les soldes de congés d'un employé pour une année donnée.
   *
   * Retourne les soldes de congés d'un employé pour une année spécifique
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getEmployeeLeaveBalancesByYear()` instead.
   *
   * This method doesn't expect any request body.
   */
  getEmployeeLeaveBalancesByYear$Response(params: GetEmployeeLeaveBalancesByYear$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<LeaveBalanceDto>>> {
    return getEmployeeLeaveBalancesByYear(this.http, this.rootUrl, params, context);
  }

  /**
   * Récupérer les soldes de congés d'un employé pour une année donnée.
   *
   * Retourne les soldes de congés d'un employé pour une année spécifique
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getEmployeeLeaveBalancesByYear$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getEmployeeLeaveBalancesByYear(params: GetEmployeeLeaveBalancesByYear$Params, context?: HttpContext): Observable<Array<LeaveBalanceDto>> {
    return this.getEmployeeLeaveBalancesByYear$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<LeaveBalanceDto>>): Array<LeaveBalanceDto> => r.body)
    );
  }

}
