/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DepartementCreateDto } from '../../models/departement-create-dto';
import { DepartementDto } from '../../models/departement-dto';

export interface CreateDepartement$Params {
      body: DepartementCreateDto
}

export function createDepartement(http: HttpClient, rootUrl: string, params: CreateDepartement$Params, context?: HttpContext): Observable<StrictHttpResponse<DepartementDto>> {
  const rb = new RequestBuilder(rootUrl, createDepartement.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DepartementDto>;
    })
  );
}

createDepartement.PATH = '/departments';
