/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Pageable } from '../../models/pageable';
import { PageEmployeeShortDto } from '../../models/page-employee-short-dto';

export interface GetEmployeesByDepartement$Params {

/**
 * ID du département
 */
  id: number;
  pageable: Pageable;
}

export function getEmployeesByDepartement(http: HttpClient, rootUrl: string, params: GetEmployeesByDepartement$Params, context?: HttpContext): Observable<StrictHttpResponse<PageEmployeeShortDto>> {
  const rb = new RequestBuilder(rootUrl, getEmployeesByDepartement.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
    rb.query('pageable', params.pageable, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageEmployeeShortDto>;
    })
  );
}

getEmployeesByDepartement.PATH = '/departments/{id}/employees';
