/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DepartementDto } from '../../models/departement-dto';

export interface SearchDepartements$Params {

/**
 * Mot-clé pour la recherche
 */
  arg0?: string;
}

export function searchDepartements(http: HttpClient, rootUrl: string, params?: SearchDepartements$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<DepartementDto>>> {
  const rb = new RequestBuilder(rootUrl, searchDepartements.PATH, 'get');
  if (params) {
    rb.query('arg0', params.arg0, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<DepartementDto>>;
    })
  );
}

searchDepartements.PATH = '/departments/search';
