/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DepartementDto } from '../../models/departement-dto';
import { DepartementUpdateDto } from '../../models/departement-update-dto';

export interface UpdateDepartement$Params {
  id: number | string;
      body: DepartementUpdateDto
}

export function updateDepartement(http: HttpClient, rootUrl: string, params: UpdateDepartement$Params, context?: HttpContext): Observable<StrictHttpResponse<DepartementDto>> {
  const rb = new RequestBuilder(rootUrl, updateDepartement.PATH, 'put');
  if (params) {
    rb.body(params.body, 'application/json');
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DepartementDto>;
    })
  );
}

updateDepartement.PATH = '/departments/{id}';
